<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms;

use GuzzleHttp\ClientInterface;
use BarisCemant\Verimor\Sms\Generated\Configuration;
use BarisCemant\Verimor\Sms\Generated\Api\BakiyeSorgulamalariApi;
use BarisCemant\Verimor\Sms\Generated\Api\BasliklarApi;
use BarisCemant\Verimor\Sms\Generated\Api\IysHizmetleriApi;
use BarisCemant\Verimor\Sms\Generated\Api\KaraListeApi;
use BarisCemant\Verimor\Sms\Generated\Api\RaporlarApi;
use BarisCemant\Verimor\Sms\Generated\Api\SmsKampanyasiApi;

final class RawApis
{
    /** @var ClientInterface */
    private $httpClient;
    /** @var Configuration */
    private $configuration;
    /** @var array<string, object> */
    private $instances = [];

    public function __construct(ClientInterface $httpClient, Configuration $configuration)
    {
        $this->httpClient = $httpClient;
        $this->configuration = $configuration;
    }

    public function bakiyeSorgulamalari(): BakiyeSorgulamalariApi
    {
        if (!isset($this->instances['BakiyeSorgulamalariApi'])) {
            $this->instances['BakiyeSorgulamalariApi'] = new BakiyeSorgulamalariApi($this->httpClient, $this->configuration);
        }
        return $this->instances['BakiyeSorgulamalariApi'];
    }
    public function basliklar(): BasliklarApi
    {
        if (!isset($this->instances['BasliklarApi'])) {
            $this->instances['BasliklarApi'] = new BasliklarApi($this->httpClient, $this->configuration);
        }
        return $this->instances['BasliklarApi'];
    }
    public function iysHizmetleri(): IysHizmetleriApi
    {
        if (!isset($this->instances['IysHizmetleriApi'])) {
            $this->instances['IysHizmetleriApi'] = new IysHizmetleriApi($this->httpClient, $this->configuration);
        }
        return $this->instances['IysHizmetleriApi'];
    }
    public function karaListe(): KaraListeApi
    {
        if (!isset($this->instances['KaraListeApi'])) {
            $this->instances['KaraListeApi'] = new KaraListeApi($this->httpClient, $this->configuration);
        }
        return $this->instances['KaraListeApi'];
    }
    public function raporlar(): RaporlarApi
    {
        if (!isset($this->instances['RaporlarApi'])) {
            $this->instances['RaporlarApi'] = new RaporlarApi($this->httpClient, $this->configuration);
        }
        return $this->instances['RaporlarApi'];
    }
    public function smsKampanyasi(): SmsKampanyasiApi
    {
        if (!isset($this->instances['SmsKampanyasiApi'])) {
            $this->instances['SmsKampanyasiApi'] = new SmsKampanyasiApi($this->httpClient, $this->configuration);
        }
        return $this->instances['SmsKampanyasiApi'];
    }
}
