<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\Sms\Generated\Api\BakiyeSorgulamalariApi;
use BarisCemant\Verimor\Sms\Generated\ApiException;


final class BalancesService
{
    /** @var BakiyeSorgulamalariApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(BakiyeSorgulamalariApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string */
    public function balance()
    {
        try {
            return $this->api->getV2Balance($this->credentials["username"], $this->credentials["password"]);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "get_v2_balance", $exception);
        }
    }
}
