<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\Sms\Generated\Api\KaraListeApi;
use BarisCemant\Verimor\Sms\Generated\ApiException;
use BarisCemant\Verimor\Sms\Dto\AddBlacklistEntryRequest;
use BarisCemant\Verimor\Sms\Dto\DeleteBlacklistEntryRequest;
use BarisCemant\Verimor\Sms\Dto\ListBlacklistEntriesRequest;

final class BlacklistService
{
    /** @var KaraListeApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(KaraListeApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string|string|string */
    public function addBlacklistEntry(AddBlacklistEntryRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->postV2Blacklists($this->credentials["username"], $this->credentials["password"], $request->phones());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "post_v2_blacklists", $exception);
        }
    }
    /** @return string|string|string|string */
    public function deleteBlacklistEntry(DeleteBlacklistEntryRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->deleteV2BlacklistsId($this->credentials["username"], $this->credentials["password"], $request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "delete_v2_blacklists_id", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\Sms\Generated\Model\GetV2Blacklists200Response */
    public function listBlacklistEntries(ListBlacklistEntriesRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getV2Blacklists($this->credentials["username"], $this->credentials["password"], $request->offset(), $request->limit());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "get_v2_blacklists", $exception);
        }
    }
}
