<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\Sms\Generated\Api\SmsKampanyasiApi;
use BarisCemant\Verimor\Sms\Generated\ApiException;
use BarisCemant\Verimor\Sms\Dto\CancelRequest;
use BarisCemant\Verimor\Sms\Dto\SendLegacyRequest;
use BarisCemant\Verimor\Sms\Dto\SendOtpRequest;
use BarisCemant\Verimor\Sms\Dto\SendRequest;

final class CampaignsService
{
    /** @var SmsKampanyasiApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(SmsKampanyasiApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string */
    public function cancel(CancelRequest $request)
    {
        $input = $request->toArray();
        $body = $input;
        $body["password"] = $this->credentials["password"];
        $body["username"] = $this->credentials["username"];
        $bodyModel = new \BarisCemant\Verimor\Sms\Generated\Model\PostV2CancelIdRequest($body);
        try {
            return $this->api->postV2CancelId($request->id(), $bodyModel);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "post_v2_cancel_id", $exception);
        }
    }
    /** @return string|string|string|string */
    public function send(SendRequest $request)
    {
        $input = $request->toArray();
        $body = $input;
        $body["password"] = $this->credentials["password"];
        $body["username"] = $this->credentials["username"];
        if (!array_key_exists("sourceAddr", $body) && array_key_exists("source_addr", $this->defaults)) {
            $body["sourceAddr"] = $this->defaults["source_addr"];
        }
        $bodyModel = new \BarisCemant\Verimor\Sms\Generated\Model\SendSmsJsonRequest($body);
        try {
            return $this->api->sendSmsJson($bodyModel);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "sendSmsJson", $exception);
        }
    }
    /** @return int|string|string|string */
    public function sendLegacy(SendLegacyRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getV2Send($this->credentials["username"], $this->credentials["password"], $request->dest(), $request->msg(), ($request->sourceAddr() !== null ? $request->sourceAddr() : ($this->defaults["source_addr"] ?? null)), $request->validFor(), $request->datacoding(), $request->isCommercial(), $request->iysRecipientType(), $request->sendAt());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "get_v2_send", $exception);
        }
    }
    /** @return string|string|string|string */
    public function sendOtp(SendOtpRequest $request)
    {
        $input = $request->toArray();
        $body = $input;
        $body["password"] = $this->credentials["password"];
        $body["username"] = $this->credentials["username"];
        $bodyModel = new \BarisCemant\Verimor\Sms\Generated\Model\OtpRequest($body);
        try {
            return $this->api->sendOtp($bodyModel);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "sendOtp", $exception);
        }
    }
}
