<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\Sms\Generated\Api\IysHizmetleriApi;
use BarisCemant\Verimor\Sms\Generated\ApiException;
use BarisCemant\Verimor\Sms\Dto\ListIysCampaignConsentsRequest;
use BarisCemant\Verimor\Sms\Dto\ListIysCampaignsRequest;
use BarisCemant\Verimor\Sms\Dto\SubmitIysConsentsRequest;

final class IysService
{
    /** @var IysHizmetleriApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(IysHizmetleriApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return \BarisCemant\Verimor\Sms\Generated\Model\GetV2IysCampaignsIdConsents200Response */
    public function listIysCampaignConsents(ListIysCampaignConsentsRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getV2IysCampaignsIdConsents($this->credentials["username"], $this->credentials["password"], $request->id(), $request->offset(), $request->limit());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "get_v2_iys_campaigns_id_consents", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\Sms\Generated\Model\GetV2IysCampaigns200Response */
    public function listIysCampaigns(ListIysCampaignsRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getV2IysCampaigns($this->credentials["username"], $this->credentials["password"], $request->offset(), $request->limit(), $request->source());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "get_v2_iys_campaigns", $exception);
        }
    }
    /** @return int|string */
    public function submitIysConsents(SubmitIysConsentsRequest $request)
    {
        $input = $request->toArray();
        $body = $input;
        $body["password"] = $this->credentials["password"];
        $body["username"] = $this->credentials["username"];
        if (!array_key_exists("sourceAddr", $body) && array_key_exists("source_addr", $this->defaults)) {
            $body["sourceAddr"] = $this->defaults["source_addr"];
        }
        $bodyModel = new \BarisCemant\Verimor\Sms\Generated\Model\PostV2IysConsentsJsonRequest($body);
        try {
            return $this->api->postV2IysConsentsJson($bodyModel);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "post_v2_iys_consents_json", $exception);
        }
    }
}
