<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\Sms\Generated\Api\RaporlarApi;
use BarisCemant\Verimor\Sms\Generated\ApiException;
use BarisCemant\Verimor\Sms\Dto\ListInboundMessagesRequest;
use BarisCemant\Verimor\Sms\Dto\StatusRequest;

final class ReportsService
{
    /** @var RaporlarApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(RaporlarApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return \BarisCemant\Verimor\Sms\Generated\Model\GetV2InboundMessages200ResponseInner[]|string */
    public function listInboundMessages(ListInboundMessagesRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getV2InboundMessages($this->credentials["username"], $this->credentials["password"], $request->fromTime(), $request->toTime(), $request->greaterThan());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "get_v2_inbound_messages", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\Sms\Generated\Model\GetSmsStatus200ResponseInner[]|string */
    public function status(StatusRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getSmsStatus($this->credentials["username"], $this->credentials["password"], $request->id(), $request->dest(), $request->greaterThan(), $request->customId());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "getSmsStatus", $exception);
        }
    }
}
