<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\Sms\Generated\Api\BasliklarApi;
use BarisCemant\Verimor\Sms\Generated\ApiException;


final class SenderIdsService
{
    /** @var BasliklarApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(BasliklarApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string[] */
    public function listSenderIds()
    {
        try {
            return $this->api->getV2Headers($this->credentials["username"], $this->credentials["password"]);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("sms", "get_v2_headers", $exception);
        }
    }
}
