<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\WhatsApp;

use GuzzleHttp\ClientInterface;
use BarisCemant\Verimor\WhatsApp\Generated\Configuration;
use BarisCemant\Verimor\WhatsApp\Generated\Api\HealthApi;
use BarisCemant\Verimor\WhatsApp\Generated\Api\MessagesApi;

final class RawApis
{
    /** @var ClientInterface */
    private $httpClient;
    /** @var Configuration */
    private $configuration;
    /** @var array<string, object> */
    private $instances = [];

    public function __construct(ClientInterface $httpClient, Configuration $configuration)
    {
        $this->httpClient = $httpClient;
        $this->configuration = $configuration;
    }

    public function health(): HealthApi
    {
        if (!isset($this->instances['HealthApi'])) {
            $this->instances['HealthApi'] = new HealthApi($this->httpClient, $this->configuration);
        }
        return $this->instances['HealthApi'];
    }
    public function messages(): MessagesApi
    {
        if (!isset($this->instances['MessagesApi'])) {
            $this->instances['MessagesApi'] = new MessagesApi($this->httpClient, $this->configuration);
        }
        return $this->instances['MessagesApi'];
    }
}
