<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class BridgeRequest
{
    private string $destination;
    private string $source;
    private ?int $announcementToCallee;
    private ?int $announcementToCaller;
    private ?string $callerId;
    private ?bool $recordingEnabled;
    private ?int $timeout;

    public function __construct(
        string $destination,
        string $source,
        ?int $announcementToCallee = null,
        ?int $announcementToCaller = null,
        ?string $callerId = null,
        ?bool $recordingEnabled = null,
        ?int $timeout = null
    ) {
        $this->destination = $destination;
        $this->source = $source;
        $this->announcementToCallee = $announcementToCallee;
        $this->announcementToCaller = $announcementToCaller;
        $this->callerId = $callerId;
        $this->recordingEnabled = $recordingEnabled;
        $this->timeout = $timeout;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['destination', 'source', 'announcementToCallee', 'announcementToCaller', 'callerId', 'recordingEnabled', 'timeout']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('BridgeRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('destination', $data)) {
            throw new \InvalidArgumentException('BridgeRequest requires destination');
        }
        if (!array_key_exists('source', $data)) {
            throw new \InvalidArgumentException('BridgeRequest requires source');
        }
        return new self(
            $data['destination'] ?? null,
            $data['source'] ?? null,
            $data['announcementToCallee'] ?? null,
            $data['announcementToCaller'] ?? null,
            $data['callerId'] ?? null,
            $data['recordingEnabled'] ?? null,
            $data['timeout'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'destination' => $this->destination,
            'source' => $this->source,
            'announcementToCallee' => $this->announcementToCallee,
            'announcementToCaller' => $this->announcementToCaller,
            'callerId' => $this->callerId,
            'recordingEnabled' => $this->recordingEnabled,
            'timeout' => $this->timeout,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function destination(): string
    {
        return $this->destination;
    }
    public function source(): string
    {
        return $this->source;
    }
    public function announcementToCallee(): ?int
    {
        return $this->announcementToCallee;
    }
    public function announcementToCaller(): ?int
    {
        return $this->announcementToCaller;
    }
    public function callerId(): ?string
    {
        return $this->callerId;
    }
    public function recordingEnabled(): ?bool
    {
        return $this->recordingEnabled;
    }
    public function timeout(): ?int
    {
        return $this->timeout;
    }
}
