<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class CreateContactRequest
{
    private string $name;
    private string $phone;
    private string $surname;
    private ?string $address;
    private ?string $birthday;
    private ?bool $birthdaySms;
    private ?string $companyName;
    private ?string $description;
    private ?string $email;
    private ?string $fax;
    private ?string $gender;
    private ?int $groupIds;
    private ?int $monthlySmsDay;
    private ?string $monthlySmsMessage;
    private ?string $note1;
    private ?string $note2;
    private ?string $note3;
    private ?string $note4;
    private ?string $phone1;
    private ?string $phone2;
    private ?string $salutation;
    private ?string $tckn;
    private ?string $title;
    private ?string $weddingday;
    private ?bool $weddingdaySms;

    public function __construct(
        string $name,
        string $phone,
        string $surname,
        ?string $address = null,
        ?string $birthday = null,
        ?bool $birthdaySms = null,
        ?string $companyName = null,
        ?string $description = null,
        ?string $email = null,
        ?string $fax = null,
        ?string $gender = null,
        ?int $groupIds = null,
        ?int $monthlySmsDay = null,
        ?string $monthlySmsMessage = null,
        ?string $note1 = null,
        ?string $note2 = null,
        ?string $note3 = null,
        ?string $note4 = null,
        ?string $phone1 = null,
        ?string $phone2 = null,
        ?string $salutation = null,
        ?string $tckn = null,
        ?string $title = null,
        ?string $weddingday = null,
        ?bool $weddingdaySms = null
    ) {
        $this->name = $name;
        $this->phone = $phone;
        $this->surname = $surname;
        $this->address = $address;
        $this->birthday = $birthday;
        $this->birthdaySms = $birthdaySms;
        $this->companyName = $companyName;
        $this->description = $description;
        $this->email = $email;
        $this->fax = $fax;
        $this->gender = $gender;
        $this->groupIds = $groupIds;
        $this->monthlySmsDay = $monthlySmsDay;
        $this->monthlySmsMessage = $monthlySmsMessage;
        $this->note1 = $note1;
        $this->note2 = $note2;
        $this->note3 = $note3;
        $this->note4 = $note4;
        $this->phone1 = $phone1;
        $this->phone2 = $phone2;
        $this->salutation = $salutation;
        $this->tckn = $tckn;
        $this->title = $title;
        $this->weddingday = $weddingday;
        $this->weddingdaySms = $weddingdaySms;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['name', 'phone', 'surname', 'address', 'birthday', 'birthdaySms', 'companyName', 'description', 'email', 'fax', 'gender', 'groupIds', 'monthlySmsDay', 'monthlySmsMessage', 'note1', 'note2', 'note3', 'note4', 'phone1', 'phone2', 'salutation', 'tckn', 'title', 'weddingday', 'weddingdaySms']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('CreateContactRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('name', $data)) {
            throw new \InvalidArgumentException('CreateContactRequest requires name');
        }
        if (!array_key_exists('phone', $data)) {
            throw new \InvalidArgumentException('CreateContactRequest requires phone');
        }
        if (!array_key_exists('surname', $data)) {
            throw new \InvalidArgumentException('CreateContactRequest requires surname');
        }
        return new self(
            $data['name'] ?? null,
            $data['phone'] ?? null,
            $data['surname'] ?? null,
            $data['address'] ?? null,
            $data['birthday'] ?? null,
            $data['birthdaySms'] ?? null,
            $data['companyName'] ?? null,
            $data['description'] ?? null,
            $data['email'] ?? null,
            $data['fax'] ?? null,
            $data['gender'] ?? null,
            $data['groupIds'] ?? null,
            $data['monthlySmsDay'] ?? null,
            $data['monthlySmsMessage'] ?? null,
            $data['note1'] ?? null,
            $data['note2'] ?? null,
            $data['note3'] ?? null,
            $data['note4'] ?? null,
            $data['phone1'] ?? null,
            $data['phone2'] ?? null,
            $data['salutation'] ?? null,
            $data['tckn'] ?? null,
            $data['title'] ?? null,
            $data['weddingday'] ?? null,
            $data['weddingdaySms'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'name' => $this->name,
            'phone' => $this->phone,
            'surname' => $this->surname,
            'address' => $this->address,
            'birthday' => $this->birthday,
            'birthdaySms' => $this->birthdaySms,
            'companyName' => $this->companyName,
            'description' => $this->description,
            'email' => $this->email,
            'fax' => $this->fax,
            'gender' => $this->gender,
            'groupIds' => $this->groupIds,
            'monthlySmsDay' => $this->monthlySmsDay,
            'monthlySmsMessage' => $this->monthlySmsMessage,
            'note1' => $this->note1,
            'note2' => $this->note2,
            'note3' => $this->note3,
            'note4' => $this->note4,
            'phone1' => $this->phone1,
            'phone2' => $this->phone2,
            'salutation' => $this->salutation,
            'tckn' => $this->tckn,
            'title' => $this->title,
            'weddingday' => $this->weddingday,
            'weddingdaySms' => $this->weddingdaySms,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function name(): string
    {
        return $this->name;
    }
    public function phone(): string
    {
        return $this->phone;
    }
    public function surname(): string
    {
        return $this->surname;
    }
    public function address(): ?string
    {
        return $this->address;
    }
    public function birthday(): ?string
    {
        return $this->birthday;
    }
    public function birthdaySms(): ?bool
    {
        return $this->birthdaySms;
    }
    public function companyName(): ?string
    {
        return $this->companyName;
    }
    public function description(): ?string
    {
        return $this->description;
    }
    public function email(): ?string
    {
        return $this->email;
    }
    public function fax(): ?string
    {
        return $this->fax;
    }
    public function gender(): ?string
    {
        return $this->gender;
    }
    public function groupIds(): ?int
    {
        return $this->groupIds;
    }
    public function monthlySmsDay(): ?int
    {
        return $this->monthlySmsDay;
    }
    public function monthlySmsMessage(): ?string
    {
        return $this->monthlySmsMessage;
    }
    public function note1(): ?string
    {
        return $this->note1;
    }
    public function note2(): ?string
    {
        return $this->note2;
    }
    public function note3(): ?string
    {
        return $this->note3;
    }
    public function note4(): ?string
    {
        return $this->note4;
    }
    public function phone1(): ?string
    {
        return $this->phone1;
    }
    public function phone2(): ?string
    {
        return $this->phone2;
    }
    public function salutation(): ?string
    {
        return $this->salutation;
    }
    public function tckn(): ?string
    {
        return $this->tckn;
    }
    public function title(): ?string
    {
        return $this->title;
    }
    public function weddingday(): ?string
    {
        return $this->weddingday;
    }
    public function weddingdaySms(): ?bool
    {
        return $this->weddingdaySms;
    }
}
