<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class CreateWebphoneTokenRequest
{
    private string $extension;

    public function __construct(
        string $extension
    ) {
        $this->extension = $extension;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['extension']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('CreateWebphoneTokenRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('extension', $data)) {
            throw new \InvalidArgumentException('CreateWebphoneTokenRequest requires extension');
        }
        return new self(
            $data['extension'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'extension' => $this->extension,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function extension(): string
    {
        return $this->extension;
    }
}
