<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class CreateVoicemailRecordingUrlRequest
{
    private string $uuid;

    public function __construct(
        string $uuid
    ) {
        $this->uuid = $uuid;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['uuid']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('CreateVoicemailRecordingUrlRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('uuid', $data)) {
            throw new \InvalidArgumentException('CreateVoicemailRecordingUrlRequest requires uuid');
        }
        return new self(
            $data['uuid'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'uuid' => $this->uuid,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function uuid(): string
    {
        return $this->uuid;
    }
}
