<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class CreateContactGroupRequest
{
    private string $name;

    public function __construct(
        string $name
    ) {
        $this->name = $name;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['name']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('CreateContactGroupRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('name', $data)) {
            throw new \InvalidArgumentException('CreateContactGroupRequest requires name');
        }
        return new self(
            $data['name'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'name' => $this->name,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function name(): string
    {
        return $this->name;
    }
}
