<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class CreateBlockedNumberRequest
{
    private string $number;
    private ?string $direction;

    public function __construct(
        string $number,
        ?string $direction = null
    ) {
        $this->number = $number;
        $this->direction = $direction;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['number', 'direction']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('CreateBlockedNumberRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('number', $data)) {
            throw new \InvalidArgumentException('CreateBlockedNumberRequest requires number');
        }
        return new self(
            $data['number'] ?? null,
            $data['direction'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'number' => $this->number,
            'direction' => $this->direction,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function number(): string
    {
        return $this->number;
    }
    public function direction(): ?string
    {
        return $this->direction;
    }
}
