<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class CreateIvrCampaignRequest
{
    private string $callType;
    private string $name;
    private array $phoneList;
    private ?array $activeDays;
    private ?int $callRetries;
    private ?string $cli;
    private ?string $dateRangeBegin;
    private ?string $dateRangeEnd;
    private ?int $digitRetries;
    private ?string $digitTarget0;
    private ?string $digitTarget1;
    private ?string $digitTarget2;
    private ?string $digitTarget3;
    private ?string $digitTarget4;
    private ?string $digitTarget5;
    private ?string $digitTarget6;
    private ?string $digitTarget7;
    private ?string $digitTarget8;
    private ?string $digitTarget9;
    private ?string $digitTargetSquare;
    private ?string $digitTargetStar;
    private ?int $digitTimeout;
    private ?string $invalidTarget;
    private ?bool $isCommercial;
    private ?string $iysBrandCode;
    private ?string $iysRecipientType;
    private ?int $maxThreadCount;
    private ?string $queueNumber;
    private ?bool $recordingEnabled;
    private ?int $ringTimeout;
    private ?int $threadMultiplier;
    private ?string $timeRangeBegin;
    private ?string $timeRangeEnd;
    private ?string $timeoutTarget;
    private ?string $webhookUrl;
    private ?int $welcomeAnnouncementId;

    public function __construct(
        string $callType,
        string $name,
        array $phoneList,
        ?array $activeDays = null,
        ?int $callRetries = null,
        ?string $cli = null,
        ?string $dateRangeBegin = null,
        ?string $dateRangeEnd = null,
        ?int $digitRetries = null,
        ?string $digitTarget0 = null,
        ?string $digitTarget1 = null,
        ?string $digitTarget2 = null,
        ?string $digitTarget3 = null,
        ?string $digitTarget4 = null,
        ?string $digitTarget5 = null,
        ?string $digitTarget6 = null,
        ?string $digitTarget7 = null,
        ?string $digitTarget8 = null,
        ?string $digitTarget9 = null,
        ?string $digitTargetSquare = null,
        ?string $digitTargetStar = null,
        ?int $digitTimeout = null,
        ?string $invalidTarget = null,
        ?bool $isCommercial = null,
        ?string $iysBrandCode = null,
        ?string $iysRecipientType = null,
        ?int $maxThreadCount = null,
        ?string $queueNumber = null,
        ?bool $recordingEnabled = null,
        ?int $ringTimeout = null,
        ?int $threadMultiplier = null,
        ?string $timeRangeBegin = null,
        ?string $timeRangeEnd = null,
        ?string $timeoutTarget = null,
        ?string $webhookUrl = null,
        ?int $welcomeAnnouncementId = null
    ) {
        $this->callType = $callType;
        $this->name = $name;
        $this->phoneList = $phoneList;
        $this->activeDays = $activeDays;
        $this->callRetries = $callRetries;
        $this->cli = $cli;
        $this->dateRangeBegin = $dateRangeBegin;
        $this->dateRangeEnd = $dateRangeEnd;
        $this->digitRetries = $digitRetries;
        $this->digitTarget0 = $digitTarget0;
        $this->digitTarget1 = $digitTarget1;
        $this->digitTarget2 = $digitTarget2;
        $this->digitTarget3 = $digitTarget3;
        $this->digitTarget4 = $digitTarget4;
        $this->digitTarget5 = $digitTarget5;
        $this->digitTarget6 = $digitTarget6;
        $this->digitTarget7 = $digitTarget7;
        $this->digitTarget8 = $digitTarget8;
        $this->digitTarget9 = $digitTarget9;
        $this->digitTargetSquare = $digitTargetSquare;
        $this->digitTargetStar = $digitTargetStar;
        $this->digitTimeout = $digitTimeout;
        $this->invalidTarget = $invalidTarget;
        $this->isCommercial = $isCommercial;
        $this->iysBrandCode = $iysBrandCode;
        $this->iysRecipientType = $iysRecipientType;
        $this->maxThreadCount = $maxThreadCount;
        $this->queueNumber = $queueNumber;
        $this->recordingEnabled = $recordingEnabled;
        $this->ringTimeout = $ringTimeout;
        $this->threadMultiplier = $threadMultiplier;
        $this->timeRangeBegin = $timeRangeBegin;
        $this->timeRangeEnd = $timeRangeEnd;
        $this->timeoutTarget = $timeoutTarget;
        $this->webhookUrl = $webhookUrl;
        $this->welcomeAnnouncementId = $welcomeAnnouncementId;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['callType', 'name', 'phoneList', 'activeDays', 'callRetries', 'cli', 'dateRangeBegin', 'dateRangeEnd', 'digitRetries', 'digitTarget0', 'digitTarget1', 'digitTarget2', 'digitTarget3', 'digitTarget4', 'digitTarget5', 'digitTarget6', 'digitTarget7', 'digitTarget8', 'digitTarget9', 'digitTargetSquare', 'digitTargetStar', 'digitTimeout', 'invalidTarget', 'isCommercial', 'iysBrandCode', 'iysRecipientType', 'maxThreadCount', 'queueNumber', 'recordingEnabled', 'ringTimeout', 'threadMultiplier', 'timeRangeBegin', 'timeRangeEnd', 'timeoutTarget', 'webhookUrl', 'welcomeAnnouncementId']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('CreateIvrCampaignRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('callType', $data)) {
            throw new \InvalidArgumentException('CreateIvrCampaignRequest requires callType');
        }
        if (!array_key_exists('name', $data)) {
            throw new \InvalidArgumentException('CreateIvrCampaignRequest requires name');
        }
        if (!array_key_exists('phoneList', $data)) {
            throw new \InvalidArgumentException('CreateIvrCampaignRequest requires phoneList');
        }
        return new self(
            $data['callType'] ?? null,
            $data['name'] ?? null,
            $data['phoneList'] ?? null,
            $data['activeDays'] ?? null,
            $data['callRetries'] ?? null,
            $data['cli'] ?? null,
            $data['dateRangeBegin'] ?? null,
            $data['dateRangeEnd'] ?? null,
            $data['digitRetries'] ?? null,
            $data['digitTarget0'] ?? null,
            $data['digitTarget1'] ?? null,
            $data['digitTarget2'] ?? null,
            $data['digitTarget3'] ?? null,
            $data['digitTarget4'] ?? null,
            $data['digitTarget5'] ?? null,
            $data['digitTarget6'] ?? null,
            $data['digitTarget7'] ?? null,
            $data['digitTarget8'] ?? null,
            $data['digitTarget9'] ?? null,
            $data['digitTargetSquare'] ?? null,
            $data['digitTargetStar'] ?? null,
            $data['digitTimeout'] ?? null,
            $data['invalidTarget'] ?? null,
            $data['isCommercial'] ?? null,
            $data['iysBrandCode'] ?? null,
            $data['iysRecipientType'] ?? null,
            $data['maxThreadCount'] ?? null,
            $data['queueNumber'] ?? null,
            $data['recordingEnabled'] ?? null,
            $data['ringTimeout'] ?? null,
            $data['threadMultiplier'] ?? null,
            $data['timeRangeBegin'] ?? null,
            $data['timeRangeEnd'] ?? null,
            $data['timeoutTarget'] ?? null,
            $data['webhookUrl'] ?? null,
            $data['welcomeAnnouncementId'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'callType' => $this->callType,
            'name' => $this->name,
            'phoneList' => $this->phoneList,
            'activeDays' => $this->activeDays,
            'callRetries' => $this->callRetries,
            'cli' => $this->cli,
            'dateRangeBegin' => $this->dateRangeBegin,
            'dateRangeEnd' => $this->dateRangeEnd,
            'digitRetries' => $this->digitRetries,
            'digitTarget0' => $this->digitTarget0,
            'digitTarget1' => $this->digitTarget1,
            'digitTarget2' => $this->digitTarget2,
            'digitTarget3' => $this->digitTarget3,
            'digitTarget4' => $this->digitTarget4,
            'digitTarget5' => $this->digitTarget5,
            'digitTarget6' => $this->digitTarget6,
            'digitTarget7' => $this->digitTarget7,
            'digitTarget8' => $this->digitTarget8,
            'digitTarget9' => $this->digitTarget9,
            'digitTargetSquare' => $this->digitTargetSquare,
            'digitTargetStar' => $this->digitTargetStar,
            'digitTimeout' => $this->digitTimeout,
            'invalidTarget' => $this->invalidTarget,
            'isCommercial' => $this->isCommercial,
            'iysBrandCode' => $this->iysBrandCode,
            'iysRecipientType' => $this->iysRecipientType,
            'maxThreadCount' => $this->maxThreadCount,
            'queueNumber' => $this->queueNumber,
            'recordingEnabled' => $this->recordingEnabled,
            'ringTimeout' => $this->ringTimeout,
            'threadMultiplier' => $this->threadMultiplier,
            'timeRangeBegin' => $this->timeRangeBegin,
            'timeRangeEnd' => $this->timeRangeEnd,
            'timeoutTarget' => $this->timeoutTarget,
            'webhookUrl' => $this->webhookUrl,
            'welcomeAnnouncementId' => $this->welcomeAnnouncementId,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function callType(): string
    {
        return $this->callType;
    }
    public function name(): string
    {
        return $this->name;
    }
    public function phoneList(): array
    {
        return $this->phoneList;
    }
    public function activeDays(): ?array
    {
        return $this->activeDays;
    }
    public function callRetries(): ?int
    {
        return $this->callRetries;
    }
    public function cli(): ?string
    {
        return $this->cli;
    }
    public function dateRangeBegin(): ?string
    {
        return $this->dateRangeBegin;
    }
    public function dateRangeEnd(): ?string
    {
        return $this->dateRangeEnd;
    }
    public function digitRetries(): ?int
    {
        return $this->digitRetries;
    }
    public function digitTarget0(): ?string
    {
        return $this->digitTarget0;
    }
    public function digitTarget1(): ?string
    {
        return $this->digitTarget1;
    }
    public function digitTarget2(): ?string
    {
        return $this->digitTarget2;
    }
    public function digitTarget3(): ?string
    {
        return $this->digitTarget3;
    }
    public function digitTarget4(): ?string
    {
        return $this->digitTarget4;
    }
    public function digitTarget5(): ?string
    {
        return $this->digitTarget5;
    }
    public function digitTarget6(): ?string
    {
        return $this->digitTarget6;
    }
    public function digitTarget7(): ?string
    {
        return $this->digitTarget7;
    }
    public function digitTarget8(): ?string
    {
        return $this->digitTarget8;
    }
    public function digitTarget9(): ?string
    {
        return $this->digitTarget9;
    }
    public function digitTargetSquare(): ?string
    {
        return $this->digitTargetSquare;
    }
    public function digitTargetStar(): ?string
    {
        return $this->digitTargetStar;
    }
    public function digitTimeout(): ?int
    {
        return $this->digitTimeout;
    }
    public function invalidTarget(): ?string
    {
        return $this->invalidTarget;
    }
    public function isCommercial(): ?bool
    {
        return $this->isCommercial;
    }
    public function iysBrandCode(): ?string
    {
        return $this->iysBrandCode;
    }
    public function iysRecipientType(): ?string
    {
        return $this->iysRecipientType;
    }
    public function maxThreadCount(): ?int
    {
        return $this->maxThreadCount;
    }
    public function queueNumber(): ?string
    {
        return $this->queueNumber;
    }
    public function recordingEnabled(): ?bool
    {
        return $this->recordingEnabled;
    }
    public function ringTimeout(): ?int
    {
        return $this->ringTimeout;
    }
    public function threadMultiplier(): ?int
    {
        return $this->threadMultiplier;
    }
    public function timeRangeBegin(): ?string
    {
        return $this->timeRangeBegin;
    }
    public function timeRangeEnd(): ?string
    {
        return $this->timeRangeEnd;
    }
    public function timeoutTarget(): ?string
    {
        return $this->timeoutTarget;
    }
    public function webhookUrl(): ?string
    {
        return $this->webhookUrl;
    }
    public function welcomeAnnouncementId(): ?int
    {
        return $this->welcomeAnnouncementId;
    }
}
