<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class CreateAnnouncementRequest
{
    private string $name;
    private string $sounddata;

    public function __construct(
        string $name,
        string $sounddata
    ) {
        $this->name = $name;
        $this->sounddata = $sounddata;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['name', 'sounddata']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('CreateAnnouncementRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('name', $data)) {
            throw new \InvalidArgumentException('CreateAnnouncementRequest requires name');
        }
        if (!array_key_exists('sounddata', $data)) {
            throw new \InvalidArgumentException('CreateAnnouncementRequest requires sounddata');
        }
        return new self(
            $data['name'] ?? null,
            $data['sounddata'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'name' => $this->name,
            'sounddata' => $this->sounddata,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function name(): string
    {
        return $this->name;
    }
    public function sounddata(): string
    {
        return $this->sounddata;
    }
}
