<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class CreateFaxOrderRequest
{
    private string $filedata;
    private string $remoteStationId;
    private ?string $localStationHeader;
    private ?string $localStationId;

    public function __construct(
        string $filedata,
        string $remoteStationId,
        ?string $localStationHeader = null,
        ?string $localStationId = null
    ) {
        $this->filedata = $filedata;
        $this->remoteStationId = $remoteStationId;
        $this->localStationHeader = $localStationHeader;
        $this->localStationId = $localStationId;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['filedata', 'remoteStationId', 'localStationHeader', 'localStationId']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('CreateFaxOrderRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('filedata', $data)) {
            throw new \InvalidArgumentException('CreateFaxOrderRequest requires filedata');
        }
        if (!array_key_exists('remoteStationId', $data)) {
            throw new \InvalidArgumentException('CreateFaxOrderRequest requires remoteStationId');
        }
        return new self(
            $data['filedata'] ?? null,
            $data['remoteStationId'] ?? null,
            $data['localStationHeader'] ?? null,
            $data['localStationId'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'filedata' => $this->filedata,
            'remoteStationId' => $this->remoteStationId,
            'localStationHeader' => $this->localStationHeader,
            'localStationId' => $this->localStationId,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function filedata(): string
    {
        return $this->filedata;
    }
    public function remoteStationId(): string
    {
        return $this->remoteStationId;
    }
    public function localStationHeader(): ?string
    {
        return $this->localStationHeader;
    }
    public function localStationId(): ?string
    {
        return $this->localStationId;
    }
}
