<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class CreateRecordingUrlRequest
{
    private string $callUuid;

    public function __construct(
        string $callUuid
    ) {
        $this->callUuid = $callUuid;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['callUuid']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('CreateRecordingUrlRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('callUuid', $data)) {
            throw new \InvalidArgumentException('CreateRecordingUrlRequest requires callUuid');
        }
        return new self(
            $data['callUuid'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'callUuid' => $this->callUuid,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function callUuid(): string
    {
        return $this->callUuid;
    }
}
