<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class DeleteContactRequest
{
    private int $id;

    public function __construct(
        int $id
    ) {
        $this->id = $id;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['id']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('DeleteContactRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('id', $data)) {
            throw new \InvalidArgumentException('DeleteContactRequest requires id');
        }
        return new self(
            $data['id'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'id' => $this->id,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function id(): int
    {
        return $this->id;
    }
}
