<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class ListVoicemailMessagesRequest
{
    private ?int $limit;
    private ?int $page;
    private ?string $read;
    private $startStampFrom;
    private $startStampTo;
    private ?string $userNumber;
    private ?string $uuid;

    public function __construct(
        ?int $limit = null,
        ?int $page = null,
        ?string $read = null,
        $startStampFrom = null,
        $startStampTo = null,
        ?string $userNumber = null,
        ?string $uuid = null
    ) {
        $this->limit = $limit;
        $this->page = $page;
        $this->read = $read;
        $this->startStampFrom = $startStampFrom;
        $this->startStampTo = $startStampTo;
        $this->userNumber = $userNumber;
        $this->uuid = $uuid;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['limit', 'page', 'read', 'startStampFrom', 'startStampTo', 'userNumber', 'uuid']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListVoicemailMessagesRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['limit'] ?? null,
            $data['page'] ?? null,
            $data['read'] ?? null,
            $data['startStampFrom'] ?? null,
            $data['startStampTo'] ?? null,
            $data['userNumber'] ?? null,
            $data['uuid'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'limit' => $this->limit,
            'page' => $this->page,
            'read' => $this->read,
            'startStampFrom' => $this->startStampFrom,
            'startStampTo' => $this->startStampTo,
            'userNumber' => $this->userNumber,
            'uuid' => $this->uuid,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function limit(): ?int
    {
        return $this->limit;
    }
    public function page(): ?int
    {
        return $this->page;
    }
    public function read(): ?string
    {
        return $this->read;
    }
    public function startStampFrom()
    {
        return $this->startStampFrom;
    }
    public function startStampTo()
    {
        return $this->startStampTo;
    }
    public function userNumber(): ?string
    {
        return $this->userNumber;
    }
    public function uuid(): ?string
    {
        return $this->uuid;
    }
}
