<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class ListBlockedNumbersRequest
{
    private ?int $limit;
    private ?int $page;

    public function __construct(
        ?int $limit = null,
        ?int $page = null
    ) {
        $this->limit = $limit;
        $this->page = $page;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['limit', 'page']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListBlockedNumbersRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['limit'] ?? null,
            $data['page'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'limit' => $this->limit,
            'page' => $this->page,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function limit(): ?int
    {
        return $this->limit;
    }
    public function page(): ?int
    {
        return $this->page;
    }
}
