<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class ListAgentStatusesRequest
{
    private ?string $agent;
    private ?string $queue;
    private ?string $status;

    public function __construct(
        ?string $agent = null,
        ?string $queue = null,
        ?string $status = null
    ) {
        $this->agent = $agent;
        $this->queue = $queue;
        $this->status = $status;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['agent', 'queue', 'status']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListAgentStatusesRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['agent'] ?? null,
            $data['queue'] ?? null,
            $data['status'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'agent' => $this->agent,
            'queue' => $this->queue,
            'status' => $this->status,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function agent(): ?string
    {
        return $this->agent;
    }
    public function queue(): ?string
    {
        return $this->queue;
    }
    public function status(): ?string
    {
        return $this->status;
    }
}
