<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class ListUserStatusesRequest
{
    private ?string $status;
    private ?string $user;

    public function __construct(
        ?string $status = null,
        ?string $user = null
    ) {
        $this->status = $status;
        $this->user = $user;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['status', 'user']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListUserStatusesRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['status'] ?? null,
            $data['user'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'status' => $this->status,
            'user' => $this->user,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function status(): ?string
    {
        return $this->status;
    }
    public function user(): ?string
    {
        return $this->user;
    }
}
