<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class ListFaxRecordsRequest
{
    private ?string $callerIdNumber;
    private ?string $direction;
    private ?int $limit;
    private ?string $originalDestination;
    private ?int $page;
    private $startStampFrom;
    private $startStampTo;
    private ?string $success;

    public function __construct(
        ?string $callerIdNumber = null,
        ?string $direction = null,
        ?int $limit = null,
        ?string $originalDestination = null,
        ?int $page = null,
        $startStampFrom = null,
        $startStampTo = null,
        ?string $success = null
    ) {
        $this->callerIdNumber = $callerIdNumber;
        $this->direction = $direction;
        $this->limit = $limit;
        $this->originalDestination = $originalDestination;
        $this->page = $page;
        $this->startStampFrom = $startStampFrom;
        $this->startStampTo = $startStampTo;
        $this->success = $success;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['callerIdNumber', 'direction', 'limit', 'originalDestination', 'page', 'startStampFrom', 'startStampTo', 'success']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListFaxRecordsRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['callerIdNumber'] ?? null,
            $data['direction'] ?? null,
            $data['limit'] ?? null,
            $data['originalDestination'] ?? null,
            $data['page'] ?? null,
            $data['startStampFrom'] ?? null,
            $data['startStampTo'] ?? null,
            $data['success'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'callerIdNumber' => $this->callerIdNumber,
            'direction' => $this->direction,
            'limit' => $this->limit,
            'originalDestination' => $this->originalDestination,
            'page' => $this->page,
            'startStampFrom' => $this->startStampFrom,
            'startStampTo' => $this->startStampTo,
            'success' => $this->success,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function callerIdNumber(): ?string
    {
        return $this->callerIdNumber;
    }
    public function direction(): ?string
    {
        return $this->direction;
    }
    public function limit(): ?int
    {
        return $this->limit;
    }
    public function originalDestination(): ?string
    {
        return $this->originalDestination;
    }
    public function page(): ?int
    {
        return $this->page;
    }
    public function startStampFrom()
    {
        return $this->startStampFrom;
    }
    public function startStampTo()
    {
        return $this->startStampTo;
    }
    public function success(): ?string
    {
        return $this->success;
    }
}
