<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class ListQueueUsersRequest
{
    private string $queueNumber;

    public function __construct(
        string $queueNumber
    ) {
        $this->queueNumber = $queueNumber;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['queueNumber']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListQueueUsersRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('queueNumber', $data)) {
            throw new \InvalidArgumentException('ListQueueUsersRequest requires queueNumber');
        }
        return new self(
            $data['queueNumber'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'queueNumber' => $this->queueNumber,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function queueNumber(): string
    {
        return $this->queueNumber;
    }
}
