<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class ListCdrsRequest
{
    private ?string $callerIdNumber;
    private ?string $destinationNumber;
    private ?string $direction;
    private ?int $limit;
    private ?string $missed;
    private ?int $page;
    private ?string $queue;
    private ?string $recordingPresent;
    private ?string $startStampFrom;
    private ?string $startStampTo;

    public function __construct(
        ?string $callerIdNumber = null,
        ?string $destinationNumber = null,
        ?string $direction = null,
        ?int $limit = null,
        ?string $missed = null,
        ?int $page = null,
        ?string $queue = null,
        ?string $recordingPresent = null,
        ?string $startStampFrom = null,
        ?string $startStampTo = null
    ) {
        $this->callerIdNumber = $callerIdNumber;
        $this->destinationNumber = $destinationNumber;
        $this->direction = $direction;
        $this->limit = $limit;
        $this->missed = $missed;
        $this->page = $page;
        $this->queue = $queue;
        $this->recordingPresent = $recordingPresent;
        $this->startStampFrom = $startStampFrom;
        $this->startStampTo = $startStampTo;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['callerIdNumber', 'destinationNumber', 'direction', 'limit', 'missed', 'page', 'queue', 'recordingPresent', 'startStampFrom', 'startStampTo']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListCdrsRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['callerIdNumber'] ?? null,
            $data['destinationNumber'] ?? null,
            $data['direction'] ?? null,
            $data['limit'] ?? null,
            $data['missed'] ?? null,
            $data['page'] ?? null,
            $data['queue'] ?? null,
            $data['recordingPresent'] ?? null,
            $data['startStampFrom'] ?? null,
            $data['startStampTo'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'callerIdNumber' => $this->callerIdNumber,
            'destinationNumber' => $this->destinationNumber,
            'direction' => $this->direction,
            'limit' => $this->limit,
            'missed' => $this->missed,
            'page' => $this->page,
            'queue' => $this->queue,
            'recordingPresent' => $this->recordingPresent,
            'startStampFrom' => $this->startStampFrom,
            'startStampTo' => $this->startStampTo,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function callerIdNumber(): ?string
    {
        return $this->callerIdNumber;
    }
    public function destinationNumber(): ?string
    {
        return $this->destinationNumber;
    }
    public function direction(): ?string
    {
        return $this->direction;
    }
    public function limit(): ?int
    {
        return $this->limit;
    }
    public function missed(): ?string
    {
        return $this->missed;
    }
    public function page(): ?int
    {
        return $this->page;
    }
    public function queue(): ?string
    {
        return $this->queue;
    }
    public function recordingPresent(): ?string
    {
        return $this->recordingPresent;
    }
    public function startStampFrom(): ?string
    {
        return $this->startStampFrom;
    }
    public function startStampTo(): ?string
    {
        return $this->startStampTo;
    }
}
