<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class ManageQueueUsersRequest
{
    private string $queueNumber;
    private string $userList;

    public function __construct(
        string $queueNumber,
        string $userList
    ) {
        $this->queueNumber = $queueNumber;
        $this->userList = $userList;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['queueNumber', 'userList']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ManageQueueUsersRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('queueNumber', $data)) {
            throw new \InvalidArgumentException('ManageQueueUsersRequest requires queueNumber');
        }
        if (!array_key_exists('userList', $data)) {
            throw new \InvalidArgumentException('ManageQueueUsersRequest requires userList');
        }
        return new self(
            $data['queueNumber'] ?? null,
            $data['userList'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'queueNumber' => $this->queueNumber,
            'userList' => $this->userList,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function queueNumber(): string
    {
        return $this->queueNumber;
    }
    public function userList(): string
    {
        return $this->userList;
    }
}
