<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class OriginateLegacyRequest
{
    private string $destination;
    private string $extension;
    private ?int $announcementToCallee;
    private ?int $announcementToCaller;
    private ?string $callerId;
    private ?string $customCallType;
    private ?bool $manualAnswer;
    private ?int $timeout;

    public function __construct(
        string $destination,
        string $extension,
        ?int $announcementToCallee = null,
        ?int $announcementToCaller = null,
        ?string $callerId = null,
        ?string $customCallType = null,
        ?bool $manualAnswer = null,
        ?int $timeout = null
    ) {
        $this->destination = $destination;
        $this->extension = $extension;
        $this->announcementToCallee = $announcementToCallee;
        $this->announcementToCaller = $announcementToCaller;
        $this->callerId = $callerId;
        $this->customCallType = $customCallType;
        $this->manualAnswer = $manualAnswer;
        $this->timeout = $timeout;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['destination', 'extension', 'announcementToCallee', 'announcementToCaller', 'callerId', 'customCallType', 'manualAnswer', 'timeout']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('OriginateLegacyRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('destination', $data)) {
            throw new \InvalidArgumentException('OriginateLegacyRequest requires destination');
        }
        if (!array_key_exists('extension', $data)) {
            throw new \InvalidArgumentException('OriginateLegacyRequest requires extension');
        }
        return new self(
            $data['destination'] ?? null,
            $data['extension'] ?? null,
            $data['announcementToCallee'] ?? null,
            $data['announcementToCaller'] ?? null,
            $data['callerId'] ?? null,
            $data['customCallType'] ?? null,
            $data['manualAnswer'] ?? null,
            $data['timeout'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'destination' => $this->destination,
            'extension' => $this->extension,
            'announcementToCallee' => $this->announcementToCallee,
            'announcementToCaller' => $this->announcementToCaller,
            'callerId' => $this->callerId,
            'customCallType' => $this->customCallType,
            'manualAnswer' => $this->manualAnswer,
            'timeout' => $this->timeout,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function destination(): string
    {
        return $this->destination;
    }
    public function extension(): string
    {
        return $this->extension;
    }
    public function announcementToCallee(): ?int
    {
        return $this->announcementToCallee;
    }
    public function announcementToCaller(): ?int
    {
        return $this->announcementToCaller;
    }
    public function callerId(): ?string
    {
        return $this->callerId;
    }
    public function customCallType(): ?string
    {
        return $this->customCallType;
    }
    public function manualAnswer(): ?bool
    {
        return $this->manualAnswer;
    }
    public function timeout(): ?int
    {
        return $this->timeout;
    }
}
