<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class SetCallMuteRequest
{
    private string $id;
    private string $state;

    public function __construct(
        string $id,
        string $state
    ) {
        $this->id = $id;
        $this->state = $state;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['id', 'state']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('SetCallMuteRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('id', $data)) {
            throw new \InvalidArgumentException('SetCallMuteRequest requires id');
        }
        if (!array_key_exists('state', $data)) {
            throw new \InvalidArgumentException('SetCallMuteRequest requires state');
        }
        return new self(
            $data['id'] ?? null,
            $data['state'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'id' => $this->id,
            'state' => $this->state,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function id(): string
    {
        return $this->id;
    }
    public function state(): string
    {
        return $this->state;
    }
}
