<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class TransferLegacyRequest
{
    private string $id;
    private string $userNumber;

    public function __construct(
        string $id,
        string $userNumber
    ) {
        $this->id = $id;
        $this->userNumber = $userNumber;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['id', 'userNumber']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('TransferLegacyRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('id', $data)) {
            throw new \InvalidArgumentException('TransferLegacyRequest requires id');
        }
        if (!array_key_exists('userNumber', $data)) {
            throw new \InvalidArgumentException('TransferLegacyRequest requires userNumber');
        }
        return new self(
            $data['id'] ?? null,
            $data['userNumber'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'id' => $this->id,
            'userNumber' => $this->userNumber,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function id(): string
    {
        return $this->id;
    }
    public function userNumber(): string
    {
        return $this->userNumber;
    }
}
