<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class UpdateCrmIntegrationsRequest
{
    private ?string $answered;
    private ?string $hangup;
    private ?string $notificationUrl;
    private ?string $ringing;

    public function __construct(
        ?string $answered = null,
        ?string $hangup = null,
        ?string $notificationUrl = null,
        ?string $ringing = null
    ) {
        $this->answered = $answered;
        $this->hangup = $hangup;
        $this->notificationUrl = $notificationUrl;
        $this->ringing = $ringing;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['answered', 'hangup', 'notificationUrl', 'ringing']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('UpdateCrmIntegrationsRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['answered'] ?? null,
            $data['hangup'] ?? null,
            $data['notificationUrl'] ?? null,
            $data['ringing'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'answered' => $this->answered,
            'hangup' => $this->hangup,
            'notificationUrl' => $this->notificationUrl,
            'ringing' => $this->ringing,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function answered(): ?string
    {
        return $this->answered;
    }
    public function hangup(): ?string
    {
        return $this->hangup;
    }
    public function notificationUrl(): ?string
    {
        return $this->notificationUrl;
    }
    public function ringing(): ?string
    {
        return $this->ringing;
    }
}
