<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class UpdateAnnouncementRequest
{
    private string $id;
    private ?string $name;
    private ?string $sounddata;

    public function __construct(
        string $id,
        ?string $name = null,
        ?string $sounddata = null
    ) {
        $this->id = $id;
        $this->name = $name;
        $this->sounddata = $sounddata;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['id', 'name', 'sounddata']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('UpdateAnnouncementRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('id', $data)) {
            throw new \InvalidArgumentException('UpdateAnnouncementRequest requires id');
        }
        return new self(
            $data['id'] ?? null,
            $data['name'] ?? null,
            $data['sounddata'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'id' => $this->id,
            'name' => $this->name,
            'sounddata' => $this->sounddata,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function id(): string
    {
        return $this->id;
    }
    public function name(): ?string
    {
        return $this->name;
    }
    public function sounddata(): ?string
    {
        return $this->sounddata;
    }
}
