<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class UpdateOutboundCallerIdRequest
{
    private string $callerId;
    private string $extension;

    public function __construct(
        string $callerId,
        string $extension
    ) {
        $this->callerId = $callerId;
        $this->extension = $extension;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['callerId', 'extension']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('UpdateOutboundCallerIdRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('callerId', $data)) {
            throw new \InvalidArgumentException('UpdateOutboundCallerIdRequest requires callerId');
        }
        if (!array_key_exists('extension', $data)) {
            throw new \InvalidArgumentException('UpdateOutboundCallerIdRequest requires extension');
        }
        return new self(
            $data['callerId'] ?? null,
            $data['extension'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'callerId' => $this->callerId,
            'extension' => $this->extension,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function callerId(): string
    {
        return $this->callerId;
    }
    public function extension(): string
    {
        return $this->extension;
    }
}
