<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class UpdateIvrCampaignRequest
{
    private string $id;
    private string $status;

    public function __construct(
        string $id,
        string $status
    ) {
        $this->id = $id;
        $this->status = $status;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['id', 'status']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('UpdateIvrCampaignRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('id', $data)) {
            throw new \InvalidArgumentException('UpdateIvrCampaignRequest requires id');
        }
        if (!array_key_exists('status', $data)) {
            throw new \InvalidArgumentException('UpdateIvrCampaignRequest requires status');
        }
        return new self(
            $data['id'] ?? null,
            $data['status'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'id' => $this->id,
            'status' => $this->status,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function id(): string
    {
        return $this->id;
    }
    public function status(): string
    {
        return $this->status;
    }
}
