<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Dto;

final class UpdateContactGroupRequest
{
    private int $id;
    private string $name;

    public function __construct(
        int $id,
        string $name
    ) {
        $this->id = $id;
        $this->name = $name;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['id', 'name']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('UpdateContactGroupRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('id', $data)) {
            throw new \InvalidArgumentException('UpdateContactGroupRequest requires id');
        }
        if (!array_key_exists('name', $data)) {
            throw new \InvalidArgumentException('UpdateContactGroupRequest requires name');
        }
        return new self(
            $data['id'] ?? null,
            $data['name'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'id' => $this->id,
            'name' => $this->name,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function id(): int
    {
        return $this->id;
    }
    public function name(): string
    {
        return $this->name;
    }
}
