<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi;

use GuzzleHttp\ClientInterface;
use BarisCemant\Verimor\SwitchApi\Generated\Configuration;
use BarisCemant\Verimor\SwitchApi\Generated\Api\AnonsYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\CagriYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\CrmEntegrasyonuApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\DisNumaralarYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\FaksYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\KaraListeYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\KullaniciYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\KuyrukYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\OtomatikAramaKampanyalariApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\RaporlamaVeKayitlarApi;
use BarisCemant\Verimor\SwitchApi\Generated\Api\RehberYonetimiApi;

final class RawApis
{
    /** @var ClientInterface */
    private $httpClient;
    /** @var Configuration */
    private $configuration;
    /** @var array<string, object> */
    private $instances = [];

    public function __construct(ClientInterface $httpClient, Configuration $configuration)
    {
        $this->httpClient = $httpClient;
        $this->configuration = $configuration;
    }

    public function anonsYonetimi(): AnonsYonetimiApi
    {
        if (!isset($this->instances['AnonsYonetimiApi'])) {
            $this->instances['AnonsYonetimiApi'] = new AnonsYonetimiApi($this->httpClient, $this->configuration);
        }
        return $this->instances['AnonsYonetimiApi'];
    }
    public function cagriYonetimi(): CagriYonetimiApi
    {
        if (!isset($this->instances['CagriYonetimiApi'])) {
            $this->instances['CagriYonetimiApi'] = new CagriYonetimiApi($this->httpClient, $this->configuration);
        }
        return $this->instances['CagriYonetimiApi'];
    }
    public function crmEntegrasyonu(): CrmEntegrasyonuApi
    {
        if (!isset($this->instances['CrmEntegrasyonuApi'])) {
            $this->instances['CrmEntegrasyonuApi'] = new CrmEntegrasyonuApi($this->httpClient, $this->configuration);
        }
        return $this->instances['CrmEntegrasyonuApi'];
    }
    public function disNumaralarYonetimi(): DisNumaralarYonetimiApi
    {
        if (!isset($this->instances['DisNumaralarYonetimiApi'])) {
            $this->instances['DisNumaralarYonetimiApi'] = new DisNumaralarYonetimiApi($this->httpClient, $this->configuration);
        }
        return $this->instances['DisNumaralarYonetimiApi'];
    }
    public function faksYonetimi(): FaksYonetimiApi
    {
        if (!isset($this->instances['FaksYonetimiApi'])) {
            $this->instances['FaksYonetimiApi'] = new FaksYonetimiApi($this->httpClient, $this->configuration);
        }
        return $this->instances['FaksYonetimiApi'];
    }
    public function karaListeYonetimi(): KaraListeYonetimiApi
    {
        if (!isset($this->instances['KaraListeYonetimiApi'])) {
            $this->instances['KaraListeYonetimiApi'] = new KaraListeYonetimiApi($this->httpClient, $this->configuration);
        }
        return $this->instances['KaraListeYonetimiApi'];
    }
    public function kullaniciYonetimi(): KullaniciYonetimiApi
    {
        if (!isset($this->instances['KullaniciYonetimiApi'])) {
            $this->instances['KullaniciYonetimiApi'] = new KullaniciYonetimiApi($this->httpClient, $this->configuration);
        }
        return $this->instances['KullaniciYonetimiApi'];
    }
    public function kuyrukYonetimi(): KuyrukYonetimiApi
    {
        if (!isset($this->instances['KuyrukYonetimiApi'])) {
            $this->instances['KuyrukYonetimiApi'] = new KuyrukYonetimiApi($this->httpClient, $this->configuration);
        }
        return $this->instances['KuyrukYonetimiApi'];
    }
    public function otomatikAramaKampanyalari(): OtomatikAramaKampanyalariApi
    {
        if (!isset($this->instances['OtomatikAramaKampanyalariApi'])) {
            $this->instances['OtomatikAramaKampanyalariApi'] = new OtomatikAramaKampanyalariApi($this->httpClient, $this->configuration);
        }
        return $this->instances['OtomatikAramaKampanyalariApi'];
    }
    public function raporlamaVeKayitlar(): RaporlamaVeKayitlarApi
    {
        if (!isset($this->instances['RaporlamaVeKayitlarApi'])) {
            $this->instances['RaporlamaVeKayitlarApi'] = new RaporlamaVeKayitlarApi($this->httpClient, $this->configuration);
        }
        return $this->instances['RaporlamaVeKayitlarApi'];
    }
    public function rehberYonetimi(): RehberYonetimiApi
    {
        if (!isset($this->instances['RehberYonetimiApi'])) {
            $this->instances['RehberYonetimiApi'] = new RehberYonetimiApi($this->httpClient, $this->configuration);
        }
        return $this->instances['RehberYonetimiApi'];
    }
}
