<?php

// GET /v1/messages/{message_ref} — Mesaj Kaydını Sorgula
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\WhatsApp\Config\WhatsAppConfig;
use BarisCemant\Verimor\WhatsApp\Dto\GetMessageRequest;
use BarisCemant\Verimor\WhatsApp\WhatsAppClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new WhatsAppClient(new WhatsAppConfig(
    (string) getenv('VERIMOR_WHATSAPP_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://wapi.verimor.com.tr'
));

$result = $client->messages()->getMessage(GetMessageRequest::fromArray([
    'messageRef' => '3f2504e0-4f89-41d3-9a0c-0305e82c3301',
]));
var_dump($result);
