<?php

// POST /v1/messages/otp — OTP / Kimlik Doğrulama Mesajı Gönder
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\WhatsApp\Config\WhatsAppConfig;
use BarisCemant\Verimor\WhatsApp\Dto\SendOtpRequest;
use BarisCemant\Verimor\WhatsApp\WhatsAppClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new WhatsAppClient(new WhatsAppConfig(
    (string) getenv('VERIMOR_WHATSAPP_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://wapi.verimor.com.tr'
));

$result = $client->messages()->sendOtp(SendOtpRequest::fromArray([
    'to' => '905001112233',
    'templateName' => 'siparis_onay',
]));
var_dump($result);
