<?php

// POST /v1/messages/bulk — Toplu Şablon Mesajı Gönder
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\WhatsApp\Config\WhatsAppConfig;
use BarisCemant\Verimor\WhatsApp\Dto\SendBulkRequest;
use BarisCemant\Verimor\WhatsApp\WhatsAppClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new WhatsAppClient(new WhatsAppConfig(
    (string) getenv('VERIMOR_WHATSAPP_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://wapi.verimor.com.tr'
));

$result = $client->messages()->sendBulk(SendBulkRequest::fromArray([
    'templateName' => 'odeme_hatirlatici',
    'recipients' => [
        [
            'to' => '905001112233',
        ],
    ],
]));
var_dump($result);
