<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\AnonsYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\CreateAnnouncementRequest;
use BarisCemant\Verimor\SwitchApi\Dto\DeleteAnnouncementRequest;
use BarisCemant\Verimor\SwitchApi\Dto\UpdateAnnouncementRequest;

final class AnnouncementsService
{
    /** @var AnonsYonetimiApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(AnonsYonetimiApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string|string|string */
    public function createAnnouncement(CreateAnnouncementRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createAnnouncement($request->name(), $request->sounddata());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createAnnouncement", $exception);
        }
    }
    /** @return string|string|string */
    public function deleteAnnouncement(DeleteAnnouncementRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->deleteAnnouncement($request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "deleteAnnouncement", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\GetAnnouncements200ResponseInner[] */
    public function listAnnouncements()
    {
        try {
            return $this->api->getAnnouncements();
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getAnnouncements", $exception);
        }
    }
    /** @return string|string|string */
    public function updateAnnouncement(UpdateAnnouncementRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->updateAnnouncement($request->id(), $request->name(), $request->sounddata());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "updateAnnouncement", $exception);
        }
    }
}
