<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\KaraListeYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\CreateBlockedNumberRequest;
use BarisCemant\Verimor\SwitchApi\Dto\DeleteBlockedNumberRequest;
use BarisCemant\Verimor\SwitchApi\Dto\ListBlockedNumbersRequest;

final class BlacklistService
{
    /** @var KaraListeYonetimiApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(KaraListeYonetimiApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string|string|string */
    public function createBlockedNumber(CreateBlockedNumberRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createBlockedNumber($request->number(), $request->direction());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createBlockedNumber", $exception);
        }
    }
    /** @return string|string|string */
    public function deleteBlockedNumber(DeleteBlockedNumberRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->deleteBlockedNumber($request->number(), $request->direction());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "deleteBlockedNumber", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\ListBlockedNumbers200Response */
    public function listBlockedNumbers(ListBlockedNumbersRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->listBlockedNumbers($request->page(), $request->limit());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "listBlockedNumbers", $exception);
        }
    }
}
