<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\DisNumaralarYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\UpdateOutboundCallerIdRequest;

final class CallerIdsService
{
    /** @var DisNumaralarYonetimiApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(DisNumaralarYonetimiApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string[] */
    public function listCallerIds()
    {
        try {
            return $this->api->getCallerIds();
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getCallerIds", $exception);
        }
    }
    /** @return string|string|string */
    public function updateOutboundCallerId(UpdateOutboundCallerIdRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->updateOutboundCallerId($request->extension(), $request->callerId());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "updateOutboundCallerId", $exception);
        }
    }
}
