<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\CagriYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\AnswerLegacyRequest;
use BarisCemant\Verimor\SwitchApi\Dto\AnswerRequest;
use BarisCemant\Verimor\SwitchApi\Dto\BridgeRequest;
use BarisCemant\Verimor\SwitchApi\Dto\HangupRequest;
use BarisCemant\Verimor\SwitchApi\Dto\OriginateLegacyRequest;
use BarisCemant\Verimor\SwitchApi\Dto\OriginateRequest;
use BarisCemant\Verimor\SwitchApi\Dto\SetCallMuteRequest;
use BarisCemant\Verimor\SwitchApi\Dto\TransferLegacyRequest;
use BarisCemant\Verimor\SwitchApi\Dto\TransferRequest;

final class CallsService
{
    /** @var CagriYonetimiApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(CagriYonetimiApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string|string|string */
    public function answer(AnswerRequest $request)
    {
        $input = $request->toArray();
        $body = $input;
        $bodyModel = new \BarisCemant\Verimor\SwitchApi\Generated\Model\AnswerCallPostRequest($body);
        try {
            return $this->api->answerCallPost($bodyModel);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "answerCallPost", $exception);
        }
    }
    /** @return string|string|string */
    public function answerLegacy(AnswerLegacyRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->answerCall($request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "answerCall", $exception);
        }
    }
    /** @return string|string|string */
    public function bridge(BridgeRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createBridge($request->source(), $request->destination(), $request->callerId(), $request->timeout(), $request->announcementToCaller(), $request->announcementToCallee(), $request->recordingEnabled());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createBridge", $exception);
        }
    }
    /** @return string|string|string */
    public function hangup(HangupRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->hangupCall($request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "hangupCall", $exception);
        }
    }
    /** @return string|string */
    public function originate(OriginateRequest $request)
    {
        $input = $request->toArray();
        $body = $input;
        $bodyModel = new \BarisCemant\Verimor\SwitchApi\Generated\Model\OriginateCallPostRequest($body);
        try {
            return $this->api->originateCallPost($bodyModel);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "originateCallPost", $exception);
        }
    }
    /** @return string|string|string */
    public function originateLegacy(OriginateLegacyRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->originateCall($request->extension(), $request->destination(), $request->callerId(), $request->manualAnswer(), $request->timeout(), $request->announcementToCallee(), $request->announcementToCaller(), $request->customCallType());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "originateCall", $exception);
        }
    }
    /** @return string|string|string */
    public function setCallMute(SetCallMuteRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->muteCall($request->id(), $request->state());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "muteCall", $exception);
        }
    }
    /** @return string|string|string */
    public function transfer(TransferRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->transferCallPost($request->id(), $request->userNumber());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "transferCallPost", $exception);
        }
    }
    /** @return string|string|string */
    public function transferLegacy(TransferLegacyRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->transferCall($request->id(), $request->userNumber());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "transferCall", $exception);
        }
    }
}
