<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\RehberYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\CreateContactGroupRequest;
use BarisCemant\Verimor\SwitchApi\Dto\CreateContactRequest;
use BarisCemant\Verimor\SwitchApi\Dto\DeleteContactGroupRequest;
use BarisCemant\Verimor\SwitchApi\Dto\DeleteContactRequest;
use BarisCemant\Verimor\SwitchApi\Dto\ListContactsRequest;
use BarisCemant\Verimor\SwitchApi\Dto\UpdateContactGroupRequest;
use BarisCemant\Verimor\SwitchApi\Dto\UpdateContactRequest;

final class ContactsService
{
    /** @var RehberYonetimiApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(RehberYonetimiApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string|string|string */
    public function createContact(CreateContactRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createContact($request->name(), $request->surname(), $request->phone(), $request->salutation(), $request->tckn(), $request->description(), $request->phone1(), $request->email(), $request->title(), $request->phone2(), $request->fax(), $request->gender(), $request->birthday(), $request->birthdaySms(), $request->weddingday(), $request->weddingdaySms(), $request->address(), $request->note1(), $request->note2(), $request->note3(), $request->note4(), $request->companyName(), $request->monthlySmsDay(), $request->monthlySmsMessage(), $request->groupIds());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createContact", $exception);
        }
    }
    /** @return string|string|string */
    public function createContactGroup(CreateContactGroupRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createContactGroup($request->name());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createContactGroup", $exception);
        }
    }
    /** @return string|string|string */
    public function deleteContact(DeleteContactRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->deleteContact($request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "deleteContact", $exception);
        }
    }
    /** @return string|string|string */
    public function deleteContactGroup(DeleteContactGroupRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->deleteContactGroup($request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "deleteContactGroup", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\ListContactGroups200ResponseInner[] */
    public function listContactGroups()
    {
        try {
            return $this->api->listContactGroups();
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "listContactGroups", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\ListContacts200Response */
    public function listContacts(ListContactsRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->listContacts($request->page(), $request->limit());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "listContacts", $exception);
        }
    }
    /** @return string|string|string */
    public function updateContact(UpdateContactRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->updateContact($request->id(), $request->salutation(), $request->name(), $request->surname(), $request->tckn(), $request->description(), $request->phone(), $request->phone1(), $request->email(), $request->title(), $request->phone2(), $request->fax(), $request->gender(), $request->birthday(), $request->birthdaySms(), $request->weddingday(), $request->weddingdaySms(), $request->address(), $request->note1(), $request->note2(), $request->note3(), $request->note4(), $request->companyName(), $request->monthlySmsDay(), $request->monthlySmsMessage(), $request->groupIds());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "updateContact", $exception);
        }
    }
    /** @return string|string|string */
    public function updateContactGroup(UpdateContactGroupRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->updateContactGroup($request->id(), $request->name());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "updateContactGroup", $exception);
        }
    }
}
