<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\CrmEntegrasyonuApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\UpdateCrmIntegrationsRequest;

final class CrmService
{
    /** @var CrmEntegrasyonuApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(CrmEntegrasyonuApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\GetCrmIntegrations200Response */
    public function getCrmIntegrations()
    {
        try {
            return $this->api->getCrmIntegrations();
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getCrmIntegrations", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\WebhookPayloadExamples200Response */
    public function getWebhookPayloadExamples()
    {
        try {
            return $this->api->webhookPayloadExamples();
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "webhookPayloadExamples", $exception);
        }
    }
    /** @return string|string|string */
    public function updateCrmIntegrations(UpdateCrmIntegrationsRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->updateCrmIntegrations($request->ringing(), $request->answered(), $request->hangup(), $request->notificationUrl());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "updateCrmIntegrations", $exception);
        }
    }
}
