<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\FaksYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\CreateFaxDocumentUrlRequest;
use BarisCemant\Verimor\SwitchApi\Dto\CreateFaxOrderRequest;
use BarisCemant\Verimor\SwitchApi\Dto\DownloadFaxDocumentRequest;
use BarisCemant\Verimor\SwitchApi\Dto\ListFaxOrdersRequest;
use BarisCemant\Verimor\SwitchApi\Dto\ListFaxRecordsRequest;

final class FaxService
{
    /** @var FaksYonetimiApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(FaksYonetimiApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string|string|string */
    public function createFaxDocumentUrl(CreateFaxDocumentUrlRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createFaxDocumentUrl($request->callUuid());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createFaxDocumentUrl", $exception);
        }
    }
    /** @return string */
    public function createFaxOrder(CreateFaxOrderRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createFaxOrder($request->remoteStationId(), $request->filedata(), $request->localStationId(), $request->localStationHeader());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createFaxOrder", $exception);
        }
    }
    /** @return \SplFileObject */
    public function downloadFaxDocument(DownloadFaxDocumentRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->downloadFaxDocument($request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "downloadFaxDocument", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\ListFaxOrders200Response */
    public function listFaxOrders(ListFaxOrdersRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->listFaxOrders($request->page(), $request->limit());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "listFaxOrders", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\ListFdrs200Response */
    public function listFaxRecords(ListFaxRecordsRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->listFdrs($request->startStampFrom(), $request->startStampTo(), $request->direction(), $request->callerIdNumber(), $request->originalDestination(), $request->success(), $request->page(), $request->limit());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "listFdrs", $exception);
        }
    }
}
