<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\OtomatikAramaKampanyalariApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\CreateIvrCampaignRequest;
use BarisCemant\Verimor\SwitchApi\Dto\DeleteIvrCampaignRequest;
use BarisCemant\Verimor\SwitchApi\Dto\UpdateIvrCampaignRequest;

final class IvrCampaignsService
{
    /** @var OtomatikAramaKampanyalariApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(OtomatikAramaKampanyalariApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string|string|string|string */
    public function createIvrCampaign(CreateIvrCampaignRequest $request)
    {
        $input = $request->toArray();
        $body = $input;
        $bodyModel = new \BarisCemant\Verimor\SwitchApi\Generated\Model\CreateIvrCampaignRequest($body);
        try {
            return $this->api->createIvrCampaign($bodyModel);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createIvrCampaign", $exception);
        }
    }
    /** @return string|string|string|string */
    public function deleteIvrCampaign(DeleteIvrCampaignRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->deleteIvrCampaign($request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "deleteIvrCampaign", $exception);
        }
    }
    /** @return string|string|string|string|string */
    public function updateIvrCampaign(UpdateIvrCampaignRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->updateIvrCampaign($request->id(), $request->status());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "updateIvrCampaign", $exception);
        }
    }
}
