<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\KuyrukYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\ListQueueUsersRequest;
use BarisCemant\Verimor\SwitchApi\Dto\ManageQueueUsersRequest;

final class QueuesService
{
    /** @var KuyrukYonetimiApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(KuyrukYonetimiApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\GetQueuesPending200ResponseInner[] */
    public function listQueuePendingCalls()
    {
        try {
            return $this->api->getQueuesPending();
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getQueuesPending", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\GetQueueUserList200ResponseInner[] */
    public function listQueueUsers(ListQueueUsersRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getQueueUserList($request->queueNumber());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getQueueUserList", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\GetQueues200ResponseInner[] */
    public function listQueues()
    {
        try {
            return $this->api->getQueues();
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getQueues", $exception);
        }
    }
    /** @return string|string|string|string */
    public function manageQueueUsers(ManageQueueUsersRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->manageQueueUsers($request->queueNumber(), $request->userList());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "manageQueueUsers", $exception);
        }
    }
}
