<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\RaporlamaVeKayitlarApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\CreateRecordingUrlRequest;
use BarisCemant\Verimor\SwitchApi\Dto\CreateVoicemailRecordingUrlRequest;
use BarisCemant\Verimor\SwitchApi\Dto\GetCdrRequest;
use BarisCemant\Verimor\SwitchApi\Dto\ListCdrsRequest;
use BarisCemant\Verimor\SwitchApi\Dto\ListVoicemailMessagesRequest;

final class RecordsService
{
    /** @var RaporlamaVeKayitlarApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(RaporlamaVeKayitlarApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string|string|string */
    public function createRecordingUrl(CreateRecordingUrlRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createRecordingUrl($request->callUuid());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createRecordingUrl", $exception);
        }
    }
    /** @return string|string|string */
    public function createVoicemailRecordingUrl(CreateVoicemailRecordingUrlRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createVoicemailRecordingUrl($request->uuid());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createVoicemailRecordingUrl", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\GetCdr200Response */
    public function getCdr(GetCdrRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getCdr($request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getCdr", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\GetCdrs200Response */
    public function listCdrs(ListCdrsRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getCdrs($request->startStampFrom(), $request->startStampTo(), $request->recordingPresent(), $request->direction(), $request->callerIdNumber(), $request->destinationNumber(), $request->missed(), $request->queue(), $request->page(), $request->limit());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getCdrs", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\GetVoicemailMessages200Response */
    public function listVoicemailMessages(ListVoicemailMessagesRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getVoicemailMessages($request->startStampFrom(), $request->startStampTo(), $request->read(), $request->userNumber(), $request->uuid(), $request->page(), $request->limit());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getVoicemailMessages", $exception);
        }
    }
}
