<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\SwitchApi\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\SwitchApi\Generated\Api\KullaniciYonetimiApi;
use BarisCemant\Verimor\SwitchApi\Generated\ApiException;
use BarisCemant\Verimor\SwitchApi\Dto\CreateWebphoneTokenRequest;
use BarisCemant\Verimor\SwitchApi\Dto\GetExtensionRequest;
use BarisCemant\Verimor\SwitchApi\Dto\ListAgentStatusesRequest;
use BarisCemant\Verimor\SwitchApi\Dto\ListUserStatusesRequest;
use BarisCemant\Verimor\SwitchApi\Dto\SetDndRequest;

final class UsersService
{
    /** @var KullaniciYonetimiApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(KullaniciYonetimiApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return string|string|string */
    public function createWebphoneToken(CreateWebphoneTokenRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createWebphoneToken($request->extension());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createWebphoneToken", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\GetExtension200Response|string|string */
    public function getExtension(GetExtensionRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->getExtension($request->id());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "getExtension", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\ListAgentStatuses200ResponseInner[] */
    public function listAgentStatuses(ListAgentStatusesRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->listAgentStatuses($request->agent(), $request->queue(), $request->status());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "listAgentStatuses", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\ListExtensions200ResponseInner[]|string */
    public function listExtensions()
    {
        try {
            return $this->api->listExtensions();
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "listExtensions", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\SwitchApi\Generated\Model\ListUserStatuses200ResponseInner[] */
    public function listUserStatuses(ListUserStatusesRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->listUserStatuses($request->user(), $request->status());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "listUserStatuses", $exception);
        }
    }
    /** @return string|string|string */
    public function setDnd(SetDndRequest $request)
    {
        $input = $request->toArray();
        try {
            return $this->api->createDnd($request->id(), $request->state());
        } catch (ApiException $exception) {
            throw ErrorMapper::map("switch", "createDnd", $exception);
        }
    }
}
