<?php

// POST /v2/blacklists — Kara Liste Ekleme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\Sms\Config\SmsConfig;
use BarisCemant\Verimor\Sms\Dto\AddBlacklistEntryRequest;
use BarisCemant\Verimor\Sms\SmsClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SmsClient(new SmsConfig(
    (string) getenv('VERIMOR_SMS_USERNAME'),
    (string) getenv('VERIMOR_SMS_PASSWORD'),
    getenv('VERIMOR_SMS_SENDER') ?: 'VERIMOR',
    getenv('VERIMOR_BASE_URL') ?: 'https://sms.verimor.com.tr'
));

$result = $client->blacklist()->addBlacklistEntry(AddBlacklistEntryRequest::fromArray([
    'phones' => '905001112233',
]));
var_dump($result);
