<?php

// GET /v2/send — SMS Gönderme (GET)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\Sms\Config\SmsConfig;
use BarisCemant\Verimor\Sms\Dto\SendLegacyRequest;
use BarisCemant\Verimor\Sms\SmsClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SmsClient(new SmsConfig(
    (string) getenv('VERIMOR_SMS_USERNAME'),
    (string) getenv('VERIMOR_SMS_PASSWORD'),
    getenv('VERIMOR_SMS_SENDER') ?: 'VERIMOR',
    getenv('VERIMOR_BASE_URL') ?: 'https://sms.verimor.com.tr'
));

$result = $client->campaigns()->sendLegacy(SendLegacyRequest::fromArray([
    'dest' => '905001112233',
    'msg' => 'Merhaba',
]));
var_dump($result);
