<?php

// POST /v2/send.json — SMS Gönderme (JSON)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\Sms\Config\SmsConfig;
use BarisCemant\Verimor\Sms\Dto\SendRequest;
use BarisCemant\Verimor\Sms\SmsClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SmsClient(new SmsConfig(
    (string) getenv('VERIMOR_SMS_USERNAME'),
    (string) getenv('VERIMOR_SMS_PASSWORD'),
    getenv('VERIMOR_SMS_SENDER') ?: 'VERIMOR',
    getenv('VERIMOR_BASE_URL') ?: 'https://sms.verimor.com.tr'
));

$result = $client->campaigns()->send(SendRequest::fromArray([
    'messages' => [
        [
            'dest' => '905111111111,905111111112',
            'msg' => 'Deneme Mesaj',
        ],
    ],
]));
var_dump($result);
