<?php

// POST /v2/iys_consents.json — İzin Yönetimi
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\Sms\Config\SmsConfig;
use BarisCemant\Verimor\Sms\Dto\SubmitIysConsentsRequest;
use BarisCemant\Verimor\Sms\SmsClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SmsClient(new SmsConfig(
    (string) getenv('VERIMOR_SMS_USERNAME'),
    (string) getenv('VERIMOR_SMS_PASSWORD'),
    getenv('VERIMOR_SMS_SENDER') ?: 'VERIMOR',
    getenv('VERIMOR_BASE_URL') ?: 'https://sms.verimor.com.tr'
));

$result = $client->iys()->submitIysConsents(SubmitIysConsentsRequest::fromArray([
    'consents' => [
        [
            'type' => 'MESAJ',
            'source' => 'HS_WEB',
            'status' => 'ONAY',
            'recipient_type' => 'BIREYSEL',
            'consent_date' => '2022-04-14 13:30:30',
            'recipient' => '905001112233',
        ],
    ],
]));
var_dump($result);
