<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Dto;

final class AddBlacklistEntryRequest
{
    private string $phones;

    public function __construct(
        string $phones
    ) {
        $this->phones = $phones;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['phones']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('AddBlacklistEntryRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('phones', $data)) {
            throw new \InvalidArgumentException('AddBlacklistEntryRequest requires phones');
        }
        return new self(
            $data['phones'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'phones' => $this->phones,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function phones(): string
    {
        return $this->phones;
    }
}
