<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Dto;

final class ListInboundMessagesRequest
{
    private ?string $fromTime;
    private ?int $greaterThan;
    private ?string $toTime;

    public function __construct(
        ?string $fromTime = null,
        ?int $greaterThan = null,
        ?string $toTime = null
    ) {
        $this->fromTime = $fromTime;
        $this->greaterThan = $greaterThan;
        $this->toTime = $toTime;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['fromTime', 'greaterThan', 'toTime']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListInboundMessagesRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['fromTime'] ?? null,
            $data['greaterThan'] ?? null,
            $data['toTime'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'fromTime' => $this->fromTime,
            'greaterThan' => $this->greaterThan,
            'toTime' => $this->toTime,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function fromTime(): ?string
    {
        return $this->fromTime;
    }
    public function greaterThan(): ?int
    {
        return $this->greaterThan;
    }
    public function toTime(): ?string
    {
        return $this->toTime;
    }
}
