<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Dto;

final class ListIysCampaignConsentsRequest
{
    private int $id;
    private ?int $limit;
    private ?int $offset;

    public function __construct(
        int $id,
        ?int $limit = null,
        ?int $offset = null
    ) {
        $this->id = $id;
        $this->limit = $limit;
        $this->offset = $offset;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['id', 'limit', 'offset']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListIysCampaignConsentsRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('id', $data)) {
            throw new \InvalidArgumentException('ListIysCampaignConsentsRequest requires id');
        }
        return new self(
            $data['id'] ?? null,
            $data['limit'] ?? null,
            $data['offset'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'id' => $this->id,
            'limit' => $this->limit,
            'offset' => $this->offset,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function id(): int
    {
        return $this->id;
    }
    public function limit(): ?int
    {
        return $this->limit;
    }
    public function offset(): ?int
    {
        return $this->offset;
    }
}
