<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Dto;

final class ListBlacklistEntriesRequest
{
    private ?int $limit;
    private ?int $offset;

    public function __construct(
        ?int $limit = null,
        ?int $offset = null
    ) {
        $this->limit = $limit;
        $this->offset = $offset;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['limit', 'offset']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListBlacklistEntriesRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['limit'] ?? null,
            $data['offset'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'limit' => $this->limit,
            'offset' => $this->offset,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function limit(): ?int
    {
        return $this->limit;
    }
    public function offset(): ?int
    {
        return $this->offset;
    }
}
