<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Dto;

final class SendRequest
{
    private array $messages;
    private ?bool $addRet;
    private ?string $customId;
    private ?int $datacoding;
    private ?bool $isCommercial;
    private ?string $iysRecipientType;
    private ?string $sendAt;
    private ?string $sourceAddr;
    private ?string $validFor;

    public function __construct(
        array $messages,
        ?bool $addRet = null,
        ?string $customId = null,
        ?int $datacoding = null,
        ?bool $isCommercial = null,
        ?string $iysRecipientType = null,
        ?string $sendAt = null,
        ?string $sourceAddr = null,
        ?string $validFor = null
    ) {
        $this->messages = $messages;
        $this->addRet = $addRet;
        $this->customId = $customId;
        $this->datacoding = $datacoding;
        $this->isCommercial = $isCommercial;
        $this->iysRecipientType = $iysRecipientType;
        $this->sendAt = $sendAt;
        $this->sourceAddr = $sourceAddr;
        $this->validFor = $validFor;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['messages', 'addRet', 'customId', 'datacoding', 'isCommercial', 'iysRecipientType', 'sendAt', 'sourceAddr', 'validFor']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('SendRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('messages', $data)) {
            throw new \InvalidArgumentException('SendRequest requires messages');
        }
        return new self(
            $data['messages'] ?? null,
            $data['addRet'] ?? null,
            $data['customId'] ?? null,
            $data['datacoding'] ?? null,
            $data['isCommercial'] ?? null,
            $data['iysRecipientType'] ?? null,
            $data['sendAt'] ?? null,
            $data['sourceAddr'] ?? null,
            $data['validFor'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'messages' => $this->messages,
            'addRet' => $this->addRet,
            'customId' => $this->customId,
            'datacoding' => $this->datacoding,
            'isCommercial' => $this->isCommercial,
            'iysRecipientType' => $this->iysRecipientType,
            'sendAt' => $this->sendAt,
            'sourceAddr' => $this->sourceAddr,
            'validFor' => $this->validFor,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function messages(): array
    {
        return $this->messages;
    }
    public function addRet(): ?bool
    {
        return $this->addRet;
    }
    public function customId(): ?string
    {
        return $this->customId;
    }
    public function datacoding(): ?int
    {
        return $this->datacoding;
    }
    public function isCommercial(): ?bool
    {
        return $this->isCommercial;
    }
    public function iysRecipientType(): ?string
    {
        return $this->iysRecipientType;
    }
    public function sendAt(): ?string
    {
        return $this->sendAt;
    }
    public function sourceAddr(): ?string
    {
        return $this->sourceAddr;
    }
    public function validFor(): ?string
    {
        return $this->validFor;
    }
}
