<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Dto;

final class SendOtpRequest
{
    private string $dest;
    private ?string $code;
    private ?string $customId;
    private ?int $datacoding;
    private ?string $header;
    private ?string $lang;
    private ?string $msg;

    public function __construct(
        string $dest,
        ?string $code = null,
        ?string $customId = null,
        ?int $datacoding = null,
        ?string $header = null,
        ?string $lang = null,
        ?string $msg = null
    ) {
        $this->dest = $dest;
        $this->code = $code;
        $this->customId = $customId;
        $this->datacoding = $datacoding;
        $this->header = $header;
        $this->lang = $lang;
        $this->msg = $msg;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['dest', 'code', 'customId', 'datacoding', 'header', 'lang', 'msg']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('SendOtpRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('dest', $data)) {
            throw new \InvalidArgumentException('SendOtpRequest requires dest');
        }
        return new self(
            $data['dest'] ?? null,
            $data['code'] ?? null,
            $data['customId'] ?? null,
            $data['datacoding'] ?? null,
            $data['header'] ?? null,
            $data['lang'] ?? null,
            $data['msg'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'dest' => $this->dest,
            'code' => $this->code,
            'customId' => $this->customId,
            'datacoding' => $this->datacoding,
            'header' => $this->header,
            'lang' => $this->lang,
            'msg' => $this->msg,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function dest(): string
    {
        return $this->dest;
    }
    public function code(): ?string
    {
        return $this->code;
    }
    public function customId(): ?string
    {
        return $this->customId;
    }
    public function datacoding(): ?int
    {
        return $this->datacoding;
    }
    public function header(): ?string
    {
        return $this->header;
    }
    public function lang(): ?string
    {
        return $this->lang;
    }
    public function msg(): ?string
    {
        return $this->msg;
    }
}
