<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Dto;

final class SendLegacyRequest
{
    private string $dest;
    private string $msg;
    private ?int $datacoding;
    private ?bool $isCommercial;
    private ?string $iysRecipientType;
    private ?string $sendAt;
    private ?string $sourceAddr;
    private ?string $validFor;

    public function __construct(
        string $dest,
        string $msg,
        ?int $datacoding = null,
        ?bool $isCommercial = null,
        ?string $iysRecipientType = null,
        ?string $sendAt = null,
        ?string $sourceAddr = null,
        ?string $validFor = null
    ) {
        $this->dest = $dest;
        $this->msg = $msg;
        $this->datacoding = $datacoding;
        $this->isCommercial = $isCommercial;
        $this->iysRecipientType = $iysRecipientType;
        $this->sendAt = $sendAt;
        $this->sourceAddr = $sourceAddr;
        $this->validFor = $validFor;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['dest', 'msg', 'datacoding', 'isCommercial', 'iysRecipientType', 'sendAt', 'sourceAddr', 'validFor']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('SendLegacyRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('dest', $data)) {
            throw new \InvalidArgumentException('SendLegacyRequest requires dest');
        }
        if (!array_key_exists('msg', $data)) {
            throw new \InvalidArgumentException('SendLegacyRequest requires msg');
        }
        return new self(
            $data['dest'] ?? null,
            $data['msg'] ?? null,
            $data['datacoding'] ?? null,
            $data['isCommercial'] ?? null,
            $data['iysRecipientType'] ?? null,
            $data['sendAt'] ?? null,
            $data['sourceAddr'] ?? null,
            $data['validFor'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'dest' => $this->dest,
            'msg' => $this->msg,
            'datacoding' => $this->datacoding,
            'isCommercial' => $this->isCommercial,
            'iysRecipientType' => $this->iysRecipientType,
            'sendAt' => $this->sendAt,
            'sourceAddr' => $this->sourceAddr,
            'validFor' => $this->validFor,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function dest(): string
    {
        return $this->dest;
    }
    public function msg(): string
    {
        return $this->msg;
    }
    public function datacoding(): ?int
    {
        return $this->datacoding;
    }
    public function isCommercial(): ?bool
    {
        return $this->isCommercial;
    }
    public function iysRecipientType(): ?string
    {
        return $this->iysRecipientType;
    }
    public function sendAt(): ?string
    {
        return $this->sendAt;
    }
    public function sourceAddr(): ?string
    {
        return $this->sourceAddr;
    }
    public function validFor(): ?string
    {
        return $this->validFor;
    }
}
