<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Dto;

final class StatusRequest
{
    private ?string $customId;
    private ?string $dest;
    private ?int $greaterThan;
    private ?int $id;

    public function __construct(
        ?string $customId = null,
        ?string $dest = null,
        ?int $greaterThan = null,
        ?int $id = null
    ) {
        $this->customId = $customId;
        $this->dest = $dest;
        $this->greaterThan = $greaterThan;
        $this->id = $id;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['customId', 'dest', 'greaterThan', 'id']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('StatusRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['customId'] ?? null,
            $data['dest'] ?? null,
            $data['greaterThan'] ?? null,
            $data['id'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'customId' => $this->customId,
            'dest' => $this->dest,
            'greaterThan' => $this->greaterThan,
            'id' => $this->id,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function customId(): ?string
    {
        return $this->customId;
    }
    public function dest(): ?string
    {
        return $this->dest;
    }
    public function greaterThan(): ?int
    {
        return $this->greaterThan;
    }
    public function id(): ?int
    {
        return $this->id;
    }
}
