<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\Sms\Dto;

final class SubmitIysConsentsRequest
{
    private array $consents;
    private string $sourceAddr;

    public function __construct(
        array $consents,
        string $sourceAddr
    ) {
        $this->consents = $consents;
        $this->sourceAddr = $sourceAddr;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['consents', 'sourceAddr']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('SubmitIysConsentsRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('consents', $data)) {
            throw new \InvalidArgumentException('SubmitIysConsentsRequest requires consents');
        }
        if (!array_key_exists('sourceAddr', $data)) {
            throw new \InvalidArgumentException('SubmitIysConsentsRequest requires sourceAddr');
        }
        return new self(
            $data['consents'] ?? null,
            $data['sourceAddr'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'consents' => $this->consents,
            'sourceAddr' => $this->sourceAddr,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function consents(): array
    {
        return $this->consents;
    }
    public function sourceAddr(): string
    {
        return $this->sourceAddr;
    }
}
