<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\WhatsApp\Dto;

final class GetMessageRequest
{
    private string $messageRef;

    public function __construct(
        string $messageRef
    ) {
        $this->messageRef = $messageRef;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['messageRef']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('GetMessageRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('messageRef', $data)) {
            throw new \InvalidArgumentException('GetMessageRequest requires messageRef');
        }
        return new self(
            $data['messageRef'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'messageRef' => $this->messageRef,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function messageRef(): string
    {
        return $this->messageRef;
    }
}
