<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\WhatsApp\Dto;

final class ListMessagesRequest
{
    private ?string $category;
    private ?int $limit;
    private ?int $offset;
    private $since;
    private ?string $status;
    private ?string $templateName;
    private ?string $to;
    private $until;
    private ?string $waMessageId;

    public function __construct(
        ?string $category = null,
        ?int $limit = null,
        ?int $offset = null,
        $since = null,
        ?string $status = null,
        ?string $templateName = null,
        ?string $to = null,
        $until = null,
        ?string $waMessageId = null
    ) {
        $this->category = $category;
        $this->limit = $limit;
        $this->offset = $offset;
        $this->since = $since;
        $this->status = $status;
        $this->templateName = $templateName;
        $this->to = $to;
        $this->until = $until;
        $this->waMessageId = $waMessageId;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['category', 'limit', 'offset', 'since', 'status', 'templateName', 'to', 'until', 'waMessageId']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('ListMessagesRequest contains unknown keys: ' . implode(', ', $unknown));
        }

        return new self(
            $data['category'] ?? null,
            $data['limit'] ?? null,
            $data['offset'] ?? null,
            $data['since'] ?? null,
            $data['status'] ?? null,
            $data['templateName'] ?? null,
            $data['to'] ?? null,
            $data['until'] ?? null,
            $data['waMessageId'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'category' => $this->category,
            'limit' => $this->limit,
            'offset' => $this->offset,
            'since' => $this->since,
            'status' => $this->status,
            'templateName' => $this->templateName,
            'to' => $this->to,
            'until' => $this->until,
            'waMessageId' => $this->waMessageId,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function category(): ?string
    {
        return $this->category;
    }
    public function limit(): ?int
    {
        return $this->limit;
    }
    public function offset(): ?int
    {
        return $this->offset;
    }
    public function since()
    {
        return $this->since;
    }
    public function status(): ?string
    {
        return $this->status;
    }
    public function templateName(): ?string
    {
        return $this->templateName;
    }
    public function to(): ?string
    {
        return $this->to;
    }
    public function until()
    {
        return $this->until;
    }
    public function waMessageId(): ?string
    {
        return $this->waMessageId;
    }
}
