<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\WhatsApp\Dto;

final class SendBulkRequest
{
    private array $recipients;
    private string $templateName;
    private ?string $language;

    public function __construct(
        array $recipients,
        string $templateName,
        ?string $language = null
    ) {
        $this->recipients = $recipients;
        $this->templateName = $templateName;
        $this->language = $language;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['recipients', 'templateName', 'language']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('SendBulkRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('recipients', $data)) {
            throw new \InvalidArgumentException('SendBulkRequest requires recipients');
        }
        if (!array_key_exists('templateName', $data)) {
            throw new \InvalidArgumentException('SendBulkRequest requires templateName');
        }
        return new self(
            $data['recipients'] ?? null,
            $data['templateName'] ?? null,
            $data['language'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'recipients' => $this->recipients,
            'templateName' => $this->templateName,
            'language' => $this->language,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function recipients(): array
    {
        return $this->recipients;
    }
    public function templateName(): string
    {
        return $this->templateName;
    }
    public function language(): ?string
    {
        return $this->language;
    }
}
