<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\WhatsApp\Dto;

final class SendOtpRequest
{
    private string $templateName;
    private string $to;
    private ?string $language;
    private $parameters;
    private ?bool $useTenantQueue;

    public function __construct(
        string $templateName,
        string $to,
        ?string $language = null,
        $parameters = null,
        ?bool $useTenantQueue = null
    ) {
        $this->templateName = $templateName;
        $this->to = $to;
        $this->language = $language;
        $this->parameters = $parameters;
        $this->useTenantQueue = $useTenantQueue;
    }

    public static function fromArray(array $data): self
    {
        $unknown = array_diff(array_keys($data), ['templateName', 'to', 'language', 'parameters', 'useTenantQueue']);
        if ($unknown !== []) {
            throw new \InvalidArgumentException('SendOtpRequest contains unknown keys: ' . implode(', ', $unknown));
        }
        if (!array_key_exists('templateName', $data)) {
            throw new \InvalidArgumentException('SendOtpRequest requires templateName');
        }
        if (!array_key_exists('to', $data)) {
            throw new \InvalidArgumentException('SendOtpRequest requires to');
        }
        return new self(
            $data['templateName'] ?? null,
            $data['to'] ?? null,
            $data['language'] ?? null,
            $data['parameters'] ?? null,
            $data['useTenantQueue'] ?? null
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'templateName' => $this->templateName,
            'to' => $this->to,
            'language' => $this->language,
            'parameters' => $this->parameters,
            'useTenantQueue' => $this->useTenantQueue,
        ], static function ($value): bool {
            return $value !== null;
        });
    }

    public function templateName(): string
    {
        return $this->templateName;
    }
    public function to(): string
    {
        return $this->to;
    }
    public function language(): ?string
    {
        return $this->language;
    }
    public function parameters()
    {
        return $this->parameters;
    }
    public function useTenantQueue(): ?bool
    {
        return $this->useTenantQueue;
    }
}
