<?php

// GET /answer/{id} — Çağrıyı Cevaplama (GET)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\AnswerLegacyRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->calls()->answerLegacy(AnswerLegacyRequest::fromArray([
    'id' => '736eaf7e-4cc4-44ab-8dbe-16b18e9618b1',
]));
var_dump($result);
