<?php

// POST /fax_orders — Faks Gönderimi
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\CreateFaxOrderRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->fax()->createFaxOrder(CreateFaxOrderRequest::fromArray([
    'remoteStationId' => '901234567891',
    'filedata' => 'JVBERi0xLjQK',
]));
var_dump($result);
