<?php

// POST /webphone_tokens — Dahili için Token Alma (IFrame ile kullanmak için)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\CreateWebphoneTokenRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->users()->createWebphoneToken(CreateWebphoneTokenRequest::fromArray([
    'extension' => '1001',
]));
var_dump($result);
