<?php

// POST /ivr_campaigns.json — Otomatik Arama Kampanyası Oluşturma
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\CreateIvrCampaignRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->ivrCampaigns()->createIvrCampaign(CreateIvrCampaignRequest::fromArray([
    'callType' => 'ivr',
    'name' => 'Memnuniyet anketi',
    'phoneList' => [
        [
            'phone' => '05111111111',
            'phrase' => '#429 12/05/2017 #430 102.45 #431',
            'lang' => 'tr-TR',
        ],
        [
            'phone' => '05111111112',
            'phrase' => '#429 12/05/2017 #430 65.12 #431',
            'lang' => 'tr-TR',
        ],
    ],
]));
var_dump($result);
