<?php

// POST /recording_url — Ses Kaydı için Geçici URL Oluşturma
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\CreateRecordingUrlRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->records()->createRecordingUrl(CreateRecordingUrlRequest::fromArray([
    'callUuid' => '3f2504e0-4f89-41d3-9a0c-0305e82c3301',
]));
var_dump($result);
