<?php

// POST /voicemail_recording_url — Telesekreter Ses Kaydı için Geçici URL Oluşturma
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\CreateVoicemailRecordingUrlRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->records()->createVoicemailRecordingUrl(CreateVoicemailRecordingUrlRequest::fromArray([
    'uuid' => '12345678-1234-5678-4321-123456789012',
]));
var_dump($result);
