<?php

// POST /fax_document_url — Faks Belgesi URL'si İsteme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\CreateFaxDocumentUrlRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->fax()->createFaxDocumentUrl(CreateFaxDocumentUrlRequest::fromArray([
    'callUuid' => 'e28e5d48-05d8-11e8-663a-fde60c59425c',
]));
var_dump($result);
