<?php

// DELETE /ivr_campaigns/{id}.json — Otomatik Arama Kampanyasını Silme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\DeleteIvrCampaignRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->ivrCampaigns()->deleteIvrCampaign(DeleteIvrCampaignRequest::fromArray([
    'id' => '123',
]));
var_dump($result);
