<?php

// GET /fax_document/{id} — Faks Belgesi İndirme/Görüntüleme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\DownloadFaxDocumentRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->fax()->downloadFaxDocument(DownloadFaxDocumentRequest::fromArray([
    'id' => '123',
]));
var_dump($result);
