<?php

// GET /queue/manage_users — Kuyruğa Dahili Ekleme, Çıkarma veya Yer Değiştirme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\ManageQueueUsersRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->queues()->manageQueueUsers(ManageQueueUsersRequest::fromArray([
    'queueNumber' => '200',
    'userList' => '1000,1001,1002',
]));
var_dump($result);
