<?php

// GET /mute/{id} — Çağrıyı Sessize Alma / Sesli Yapma
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\SetCallMuteRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->calls()->setCallMute(SetCallMuteRequest::fromArray([
    'id' => 'f3797dfc-a818-11e7-bf70-cb295b6663ce',
    'state' => 'on',
]));
var_dump($result);
