<?php

// GET /transfer/{id} — Çağrıyı Aktarma (GET)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\TransferLegacyRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->calls()->transferLegacy(TransferLegacyRequest::fromArray([
    'id' => 'f3797dfc-a818-11e7-bf70-cb295b6663ce',
    'userNumber' => '1000',
]));
var_dump($result);
