<?php

// GET /update_outbound_caller_id — Dahilinin Dış Numarasını (Arayan No) Değiştirme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

declare(strict_types=1);

use BarisCemant\Verimor\SwitchApi\Config\SwitchConfig;
use BarisCemant\Verimor\SwitchApi\Dto\UpdateOutboundCallerIdRequest;
use BarisCemant\Verimor\SwitchApi\SwitchClient;

require dirname(__DIR__, 3) . '/vendor/autoload.php';

$client = new SwitchClient(new SwitchConfig(
    (string) getenv('VERIMOR_SWITCH_API_KEY'),
    getenv('VERIMOR_BASE_URL') ?: 'https://api.bulutsantralim.com'
));

$result = $client->callerIds()->updateOutboundCallerId(UpdateOutboundCallerIdRequest::fromArray([
    'extension' => '1000',
    'callerId' => '90850532xxxx',
]));
var_dump($result);
