<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\WhatsApp\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\WhatsApp\Generated\Api\HealthApi;
use BarisCemant\Verimor\WhatsApp\Generated\ApiException;


final class HealthService
{
    /** @var HealthApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(HealthApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return mixed */
    public function health()
    {
        try {
            return $this->api->healthHealthGet();
        } catch (ApiException $exception) {
            throw ErrorMapper::map("whatsapp", "health_health_get", $exception);
        }
    }
}
