<?php

// Code generated by scripts/generate_php_facades.py. DO NOT EDIT.

declare(strict_types=1);

namespace BarisCemant\Verimor\WhatsApp\Service;

use BarisCemant\Verimor\Http\ErrorMapper;
use BarisCemant\Verimor\WhatsApp\Generated\Api\MessagesApi;
use BarisCemant\Verimor\WhatsApp\Generated\ApiException;
use BarisCemant\Verimor\WhatsApp\Dto\SendOtpRequest;
use BarisCemant\Verimor\WhatsApp\Dto\SendUtilityRequest;

final class MessagesService
{
    /** @var MessagesApi */
    private $api;
    /** @var array<string, string> */
    private $credentials;
    /** @var array<string, string> */
    private $defaults;

    public function __construct(MessagesApi $api, array $credentials, array $defaults = [])
    {
        $this->api = $api;
        $this->credentials = $credentials;
        $this->defaults = $defaults;
    }

    /** @return \BarisCemant\Verimor\WhatsApp\Generated\Model\MessageResponse|\BarisCemant\Verimor\WhatsApp\Generated\Model\HTTPValidationError */
    public function sendOtp(SendOtpRequest $request)
    {
        $input = $request->toArray();
        $body = $input;
        $bodyModel = new \BarisCemant\Verimor\WhatsApp\Generated\Model\TemplateMessageRequest($body);
        try {
            return $this->api->sendOtpV1MessagesOtpPost($bodyModel, $this->credentials["x-api-key"]);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("whatsapp", "send_otp_v1_messages_otp_post", $exception);
        }
    }
    /** @return \BarisCemant\Verimor\WhatsApp\Generated\Model\MessageResponse|\BarisCemant\Verimor\WhatsApp\Generated\Model\HTTPValidationError */
    public function sendUtility(SendUtilityRequest $request)
    {
        $input = $request->toArray();
        $body = $input;
        $bodyModel = new \BarisCemant\Verimor\WhatsApp\Generated\Model\TemplateMessageRequest($body);
        try {
            return $this->api->sendUtilityV1MessagesUtilityPost($bodyModel, $this->credentials["x-api-key"]);
        } catch (ApiException $exception) {
            throw ErrorMapper::map("whatsapp", "send_utility_v1_messages_utility_post", $exception);
        }
    }
}
